Task 7 mechanics of the game on canvas api
yandex-team-01/middle.game.praktikum.yandex pull request #1
Opened 2022-10-31 15:54 UTC by user14052020

### Какую задачу решаем

Механика игры на Canvas API
https://linear.app/teamproject/issue/PRA-7/igrovoj-dvizhok

Для реализации создано три файла:
1) pages/GameScreen
2) components/Game
3) logic/Game

экран Игра вызывает компонент Игра, который в свою очередь создает экземпляр класса Игра.

Класс игра с помощью обработчика событий реагирует на нажатия пользователем клавиш, чтобы перемещать соответствующего персонажа -- стрелочки для Синего персонажа, W A S D для Розового персонажа.

При нажатии клавиши добавляем ее код в массив keys, если отпустили клавишу, то удаляем эту клавишу из массива. 

После того как карта и персонажи нарисованы запускаются функции movePlayer и   handlePlayerFrame. 

movePlayer пробегается по массиву клавиш и при обнаружении допустимых для пользователей клавиш двигает соответствующего пользователя в привязанном к клавише направлении на величину равную скорости пользователя.

handlePlayerFrame в зависимости от направления движения подставляет соответствующую картинку передвижения ног.

Чтобы получить плавную картинку передвижения ног персонажа, добавлена функция StartAnimating, в которую передается fps(то, как быстро будет отрисовываться движение ног) и сохраняется значение then, затем вызывается функция animate, которая благодаря requestAnimationFrame бесконечно вызывается в цикле, соотвественно каждый раз меняется значение разницы между then и now что позволяет перерисовывать экран игры с нужной скоростью.

### Скриншоты/видяшка (если есть)
<img width="1440" alt="Screenshot 2022-10-31 at 15 36 32" src="https://user-images.githubusercontent.com/65355827/198988955-6d88781c-0c7b-4e7b-b921-58e97afc753f.png">

видео https://disk.yandex.com/i/RTfvBWtvg3fwhA
### TBD (если есть)

2022-10-31 17:08 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +function GameComponent() {
В проекте принято использовать стрелочные функции:
```suggestion
const GameComponent = () => {
```

2022-10-31 17:40 UTC, khitrind requested changes
Такс в целом хорошее начало, но стоит разделить все на логические кусочки, что можно сделать:

- Есть класс Game - задача этого класса создать все необходимые модули игры (применить конфигурацию);
- Есть всякие объекты, такие как Player к примеру у него свой класс;
- В каждом классе описывается логика поведения этого объекта;

Далее возможно несколько простых подходов, либо у все объекты наследуют некоторый общий интерфейс:

```
interface Player {
    animate: () => void;
}

class PlayerOne implements Player {
    animate: () => {
        //do smth
    }
}

class PlayerTwo implements Player {
    animate: () => {
        //do smth
    }
}



class Game {
    private playerOne: Player
    private playerTwo: Player

    constructor() {
        this.playerOne = new PlayerOne();
        this.playerTwo = new PlayerTwo();
    }
}

```

Далее логику взаимодействия между объектами можно либо описать в game, либо вынести в отдельный класс (мне скорее ближе этот вариант, что game просто все создает, а логика взаимодействия описана где-то еще)

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +  useEffect(() => {
useEffect лучше вынести в отдельный кастомный хук,  что бы стразу было понятно, что этот код работает только на маунте:
```

import {useEffect} from 'react';

/**
 * Вызывает effectCallback при маунте компонента
 */
export const useMountEffect = (effectCallback: () => (() => void) | void) => {
    // тут не должно быть зависимостей
    // eslint-disable-next-line react-hooks/exhaustive-deps
    useEffect(effectCallback, []);
};

```

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +    game.current!.StartAnimating(10);
Лучше доказать это по типам, не используя force unwrap:

const gameRef = game.current;

if (gameRef) {
    // do smth
}

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +export default GameComponent;
Договорились о том, что бы использовать именованные экспорты

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +        this.playerSprite.src = "/src/assets/images/game-player.png";
Работу с игроком выносим в отдельный класс, тут просто создается экземпляр

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +        this.playerSpriteSecond = new Image();
Точно так же, второй игрок - инстанс класса Игрок

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +    drawSprite(img:CanvasImageSource, sX:number, sY:number, sW:number, sH:number, dX:number, dY:number, dW:number, dH:number){
`img:CanvasImageSource, sX:number, sY:number, sW:number, sH:number, dX:number, dY:number, dW:number, dH:number` - это все выносим в отдельный тип в куче number легко потерять порядок

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +    handlePlayerFrame (){
Эту функцию выносим в класс игрока

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +    animate(){
В каждом классе должна быть своя animate, game просто вызывает эту функцию

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +     movePlayer(){
Так же выносим в класс игрока

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +        if (keys[38] && player.y > 100){
Что значит keys[38] - выглядит как магические циферки, давай повыносим это в enum

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +    constructor(protected canvas: HTMLCanvasElement) {
Для чего тут protected?

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +});
EOF

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +window.addEventListener("keydown", function(e){
Это должно происходить в конструкторе и в деструкторе стоит отписаться что бы предвосхитить утечки памяти

2022-10-31 17:40 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +export default class Game {
```suggestion
export class Game {
```

2022-10-31 17:42 UTC, khitrind commented
Плюс посмотри пожалуйста откуда такой chahge в package-lock и в yarn-lock, новых зависимостей в проекте же нет, это не норм

2022-11-04 08:27 UTC, user14052020 commented on packages/client/src/logic/Game/Game.tsx
> +    constructor(protected canvas: HTMLCanvasElement) {
обратил внимание, что если указать protected, то можно не указывать в переменных этого класса public canvas!: HTMLCanvasElement, мне это показалось удобным, так как меньше кода

2022-11-04 16:11 UTC, khitrind approved these changes
Давай сделаем так, это версию можно влить, что бы было хоть что-то,  но дальше в какой-нибудь день созвонимся им голосом обсудим логику решения?

2022-11-04 16:11 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +
Всю это логику  прям в отдельный класс

2022-11-04 16:11 UTC, khitrind commented on packages/client/src/logic/Game/types.ts
> +export interface gameImageProps extends Game {
Названия типов с заглавной буквы

2022-11-04 16:11 UTC, khitrind commented on packages/client/src/logic/Player/Player.tsx
> +  enum DirectionPlayerTwo {
Отступы уехали

2022-11-04 16:11 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +
Game ничего не должен знать о деталях имплементации

2022-11-04 16:11 UTC, khitrind commented on packages/client/src/logic/Player/Player.tsx
> +    ctx: CanvasRenderingContext2D;
Тут нужно описать только про те поля, про которые стоит знать Game, скорее даже методы, не нужно описывать тут все

2022-11-04 16:14 UTC, user14052020 commented
> Давай сделаем так, это версию можно влить, что бы было хоть что-то, но дальше в какой-нибудь день созвонимся им голосом обсудим логику решения?

 Хорошо, спасибо. Мне удобно созвониться в любой день с 15 до 19 по МСК

2022-11-05 10:15 UTC, Helga108 approved these changes

2022-11-05 12:38 UTC, merged