Pra 61 layout pages with comments
yandex-team-01/middle.game.praktikum.yandex pull request #10
Opened 2022-11-04 20:20 UTC by Victoriya0993

### Какую задачу решаем
Новые страницы для форума.

Добавлены:
- основная страница форума со списком тем (Forum);
- страница создания новой темы (ForumCreateTopic);
- страница с конкретной темой и комментариями к ней (ForumCommentsPage);

Дополнительно:
- создан слайс для форума;
- добавлена логика содания темы и комментариев;
- события на кнопки (переходы по страницам).

### Скриншоты/видяшка (если есть)
Первый список тем берется из json-файла

![image](https://user-images.githubusercontent.com/90398540/200066707-0cd6841e-b024-409d-80f5-b48447e8731e.png)

![image](https://user-images.githubusercontent.com/90398540/200066722-b67b24b8-bf3e-4112-948a-0c6350bd6dd0.png)

![image](https://user-images.githubusercontent.com/90398540/200066745-8b85c309-d8e6-4bd9-95a4-7d69529b51b4.png)

![image](https://user-images.githubusercontent.com/90398540/200067004-b501142b-d67f-4f74-a1eb-d7f8b642805b.png)

![image](https://user-images.githubusercontent.com/90398540/200067012-d85f4afe-66f4-45fc-8956-557437227c0b.png)

### TBD (если есть)

2022-11-04 21:30 UTC, khitrind requested changes
Привет, очень классная работа, абсолюьные пути - пушка!) Правда очень классный вклад в общую инфру проекта. Теперь по самое работе - в целом все тоже оч не плохо, но есть пара моментов которые хотелось бы поправить:

- избавиться от дублирования кода;
- вынести кусочки о которых я комментах отписал в отдельные компоненты;
- разобраться с инпутами и не лазить в html руками)

2022-11-04 21:30 UTC, khitrind commented on packages/client/package.json
> +    "react-icons": "4.6.0",
Вы обсудили с командой добавление этой либы и вообще работу с картинками? Я просто в соседнем pr от @samgxlden видел другой способ, засинхронизируйтесь пожалуйста)

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/components/BlankWindow/BlankWindow.tsx
> +export const BlankWindow = ({ children, className }: Props): JSX.Element => (
```suggestion
export const BlankWindow = ({ children, className }: Props) => (
```
Тут не обязательно писать тип TS сам его выведет)

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/components/Form/types.ts
> +  actions: ReactNode[];
Что значит actions? Не очень интуитивно понятное название(

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/components/ProtectedRoute/types.ts
>  export type Props = {
Често говоря мне кажется удобней держать тип Props в одном файле с компонентом (в целом если делать библиотеку компонентов, там действительно вытаскивают интерфес/тип в отдельный файл), но если это что-то что используется только внутри проекта, то держать тип и код рядом просто удобней (имхо)

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/Forum/Forum.tsx
>  import { TopicList } from './components/TopicList';
Тут как будто тоже можно использовать абсолютные пути

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/Forum/Forum.tsx
> +            <Button onClick={() => navigate('/loading')}>PLAY</Button>
Я бы предложил обернуть функции в useCallback - во первых они передаются в друго компонент, во вторых так можно дать им какие-то понятные название, что бы было проще понять, что тут происходит

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/Forum/components/Topic/Topic.tsx
> +  const { id, title, description, author, date, comments, views } = props.topic;
`export const Topic = ({ id, title, description, author, date, comments, views }: Props) => {`

Деструктуризацию можно сделать сразу

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/Forum/components/Topic/Topic.tsx
> +        </div>
Это можно повыносить в отдельные компоненты

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/Forum/components/Topic/Topic.tsx
> +          </div>
Это тоже можно вынести в отдельный компонент

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/Forum/components/TopicList/TopicList.tsx
> +  const topics = useAppSelector(state => state.forum.listTopics);
Почитай пожалуйста про второй аргумент в useSelector. 
Если вкратце, то либо стоит использовать [reselect](https://redux-toolkit.js.org/api/createSelector) либо передавать вторым аргументом compare function что бы не перерендеривать компонент при каждом изменение стейта. Для примитивов shallowEqual, для объектов глубокое сравнение

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/Forum/components/TopicList/TopicList.tsx
> +    <ErrorBoundary>
В данном случае я бы обернул топик в `ErrorBoundary` либо ничего не оборачивал, потому-что в твоей реализации, если упадет один топик упадет весь лист

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/ForumCommentsPage/Comment/Comment.tsx
> +        </div>
Где-то я уже видео похожий код - значит 100% надо выносить views и comments в отдельные компоненты

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/ForumCommentsPage/ForumCommentsPage.tsx
> +    );
Хорошо бы вынести эту функцию куда-нибудь в utils это же просто в полне самостоятельный форматер даты - он особого отношения к этому компоненту не имеет

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/ForumCommentsPage/ForumCommentsPage.tsx
> +          </div>
Это стоит вынести в отдельный компонент

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/ForumCommentsPage/ForumCommentsPage.tsx
> +    const input = document.getElementsByName('comment')[0] as HTMLInputElement;
Вот так точно делать не надо, вся работа с DOM идет через реакт, если приходится лезтьв html вот так руками - значит мы что-то делаем не так(  В данном случае простое решение вопроса - заводим переменную через useState и уже с ней работаем (если еще много разных вариантом, но давай пока остановимся для начала на таком)

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/ForumCommentsPage/ForumCommentsPage.tsx
> +            date: new_format_date,
Почему переменная в `snake_case`?

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/ForumCommentsPage/ForumCommentsPage.tsx
> +            <Button onClick={() => navigate('/loading')}>PLAY</Button>
Почему кнопка play ведет на роут loading?

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/ForumCreateTopic/ForumCreateTopic.tsx
> +import * as uuid from 'uuid';
Почему import *?

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/ForumCreateTopic/ForumCreateTopic.tsx
> +
Я уже видел эту функцию в коде, зачем копипастить?

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/pages/ForumCreateTopic/ForumCreateTopic.tsx
> +    const date = new Date();
Про такой способ доставания данных отписался выше

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/store/forum/ForumSlice.ts
> +      )[0];
Почему 0 элемент? Если неужно найти один единственный топик у массивов есть метод [find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

2022-11-04 21:30 UTC, khitrind commented on packages/client/src/store/forum/initialSlice.ts
> +  activeTopic: undefined,
Его можно просто не передавать

2022-11-06 07:23 UTC, DianaIvanovna commented on packages/client/src/pages/Forum/components/BlockComments/BlockComments.tsx
> +  const topic = useAppSelector(state => state.forum.activeTopic);
можно объединить [login, topic] = useAppSelector(state => [state.auth.user?.login, state.forum.activeTopic]);

2022-11-06 07:27 UTC, DianaIvanovna commented on packages/client/src/pages/Forum/components/BlockCreateTopic/BlockCreateTopic.tsx
> +  }, []);
я бы позже добавила formik чтобы самой не прописывать логику работы с формой

2022-11-06 07:34 UTC, DianaIvanovna approved these changes

2022-11-06 14:11 UTC, Victoriya0993 commented on packages/client/src/pages/Forum/components/BlockCreateTopic/BlockCreateTopic.tsx
> +  }, []);
Спасибо за рекомендацию, в следующем спринте постараюсь добавить

2022-11-06 14:44 UTC, khitrind commented on packages/client/src/pages/Forum/components/BlockComments/BlockComments.tsx
> +          </BlankWindow>
Это тоже выглядит как отдельный компонент

2022-11-06 14:46 UTC, khitrind commented on packages/client/src/pages/Forum/components/TopicList/TopicList.tsx
> +  const topics = useAppSelector(state => state.forum.listTopics);
Тут ничего не поменялось, напомни мне поговорить про это на встрече

2022-11-06 14:46 UTC, khitrind commented on packages/client/src/pages/Forum/part/Topic/Topic.tsx
> +        <div onClick={handlerGoToTopic} className={styles.topic}>
Я уже 3 раз вижу css с названием topic, чем они все отличаются?)

2022-11-06 14:47 UTC, khitrind commented on packages/client/src/store/forum/ForumSlice.ts
> +      state.listTopics.unshift(action.payload);
unshift дорогая опреация, проще читать посты с конца массива

2022-11-06 14:48 UTC, khitrind approved these changes
Сейчас апрувну, но есть пара вещей, которые надо будет на встрече обсудить

2022-11-06 15:28 UTC, merged