добавлен механизм окончания игры
yandex-team-01/middle.game.praktikum.yandex pull request #11
Opened 2022-11-05 15:11 UTC by user14052020

### Какую задачу решаем
https://linear.app/teamproject/issue/PRA-29/ekran-ili-stranica-zaversheniya-igry
PRA-29 Экран (или страница) завершения игры

1. После заполнения шкалы загрузки на 100% происходит переход на страницу игры
2. При нажатии на кнопку GAME OVER canvas перерисовывается с фоном GAME OVER и включается фоновая музыка
### Скриншоты/видяшка (если есть)

### TBD (если есть)

2022-11-05 17:37 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +          } } >GAME OVER</Button>
- Что значит кнопка game over? 
- если выйти из игры но не остановить ее, то память может утечь + непредвиденные последствия

2022-11-05 17:38 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +    public isOver = false;
Для чего флажок isOver? Это же костыль, вместо того что бы gameLoop остановить мы флажок выставляем)

2022-11-05 17:39 UTC, khitrind commented on packages/client/src/pages/GameLoadingPage/GameLoadingPage.tsx
> +  }, [progress]);
Правила линта не для того что бы из дизейблить) Для чего мы его тут задизейблили?

2022-11-05 17:39 UTC, khitrind commented on packages/client/src/pages/HomePage/components/HomeAuth/HomeAuth.tsx
> +        }}>
Button - это компонент, давай функцию обернем в useCallback, что бы каждый раз ссылка на нее не менялась

2022-11-05 17:40 UTC, khitrind requested changes
В комментах отписал

2022-11-05 17:57 UTC, DianaIvanovna commented on packages/client/src/pages/GameLoadingPage/GameLoadingPage.tsx
> +  }, [progress]);
Мне дима говорил, что лучше не использовать в данном случае useEffect а сделать так 
```
  if (progress === 100) {
    return <Navigate to="/game" />;
  }
```

2022-11-06 13:04 UTC, khitrind requested changes

2022-11-06 13:04 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +            }}>GO BACK</Button>
Тут ничего не исправлено

2022-11-06 13:04 UTC, khitrind commented on packages/client/src/logic/Player/Player.tsx
> +        this.keyDownCustom = this.keyDownCustom.bind(this);
Зачем так? Стрелочные функции сохраняют контекст

2022-11-06 13:04 UTC, khitrind commented on packages/client/src/pages/GameScreen/GameScreen.tsx
>  export function GameScreen() {
почему все через стрелочные функции, а тут через function?

2022-11-06 13:04 UTC, khitrind commented on packages/client/src/pages/HomePage/components/HomeAuth/HomeAuth.tsx
> +          }, [navigate])}>
...
https://reactjs.org/docs/hooks-rules.html

Пожалуйста почитай документацию

2022-11-07 06:54 UTC, khitrind approved these changes

2022-11-07 16:57 UTC, DianaIvanovna approved these changes

2022-11-07 16:58 UTC, merged