feat: добавила обработку столкновений + добавила класс view, sprite, npc
yandex-team-01/middle.game.praktikum.yandex pull request #15
Opened 2022-11-10 19:39 UTC by DianaIvanovna

[pra-95-обработка-столкновения-игрока](https://linear.app/teamproject/issue/PRA-95/obrabotka-stolknoveniya-igroka-s-npcobuektom-igry)

Сделано: 
- отдельный класс View для отрисовки canvas
- класс Sprinte для ожидания загрузки спрайтов и удобного хранения
- временный класс npc (он потом поменяется) 
- функция обработки столкновения игрока с npc

Я сделала небольшое видео с объяснением кода, но не смогла добавить его в ПР, поэтому вот [ссылка на видео](https://disk.yandex.ru/i/Vc6nL--2YnG2XA)
PS: извините за звук и водяной знак, время позднее и не захотелось разбираться с ним

![image](https://user-images.githubusercontent.com/60156828/201189548-9febe189-5c67-44f8-b305-a7da929dd846.png)

2022-11-11 03:11 UTC, user14052020 commented on packages/client/src/logic/Player/Player.tsx
>  export class PlayerTwo extends Player {
Удали пожалуйста класс второго пользователя, раз мы решили что для mvp нам хватит одного пользователя, а когда придет время второго пользователя едва ли этот код будет актуален к тому времени.

2022-11-11 03:15 UTC, user14052020 commented on packages/client/src/logic/Npc.ts
> +export class Npc extends NpcAbstract {
может быть в нашем случае implements вместо extends будет правильнее, как думаешь?

2022-11-11 03:23 UTC, user14052020 requested changes
Привет) Получилось здорово) Наверное стоит убрать код второго игрока раз он нам пока не нужен, чтобы не засорять и стоит разобраться extends или implements использовать в наших абстрактных классах и нужны ли нам абстрактные классы может достаточно интерфейса

2022-11-11 03:23 UTC, user14052020 commented on packages/client/src/logic/Npc.ts
> +export class Npc extends NpcAbstract {
может быть в нашем случае implements вместо extends будет правильнее, как думаешь?

2022-11-11 03:23 UTC, user14052020 commented on packages/client/src/logic/Player/Player.tsx
>  export class PlayerTwo extends Player {
Удали пожалуйста класс второго пользователя, раз мы решили что для mvp нам хватит одного пользователя, а когда придет время второго пользователя едва ли этот код будет актуален к тому времени.

2022-11-11 03:23 UTC, user14052020 commented on packages/client/src/components/Game/Game.tsx
> +  let ignore = false;
расскажи пожалуйста подробнее про ignore, сейчас не понятно для чего это и почему без этого флага нельзя

2022-11-11 07:48 UTC, DianaIvanovna commented on packages/client/src/logic/Npc.ts
> +export class Npc extends NpcAbstract {
Думаю да. Сначала планировалось, что будут  несколько классов Npc с разной логикой внутри, поэтому сделала extends. Но сейчас понятно, что хватит одного класса с переменной "тип npc"

2022-11-11 07:56 UTC, DianaIvanovna commented on packages/client/src/components/Game/Game.tsx
> +  let ignore = false;
Смотри в чем проблема, класс игры сейчас написан так: 

```
export class Game {
****
  async init() {
    console.log('init');
    await this.prepareSprites(); // асинхронная функция для загрузки всех спрайтов 
    this.start();
  }
  start() {
    console.log('start');
    this.startAnimating(10);
    this.preparePlayer();
    const updater = () => {
      this.animate();
      this.animationRequestId = requestAnimationFrame(updater); 
    };
    this.animationRequestId = requestAnimationFrame(updater); 
  }

  destruct() {
    console.log('destruct');
    cancelAnimationFrame(this.animationRequestId as number);
  }
}
```

функция useMountEffect вызывается 2 раза и  в консоли будет такая картина: 
![image](https://user-images.githubusercontent.com/60156828/201292162-0b6bd150-133f-4aec-a549-c73898ecde3b.png)

Проблема в том, что функция init асинхронная. Сначала вызывается загрузка спрайтов а после выполнения функция start, где запускается цикл отрисовки. а функция destruct должна очистить цикл отрисовки

в консоли видно, что вызывается функция init, а после этого сразу destruct  и она не очищает цикл отрисовки , т к start еще не запустилась. Потом вызывается второй раз функция init и два раза функция start. 
Из-за двойного вызова start у нас получается 2 цикла отрисовки, один из которых нельзя удалить. 

Чтобы решить эту проблему нужно либо во всем файле убрать StrictMode, либо ignore с игнорированием второго вызова useMountEffect

2022-11-11 09:57 UTC, khitrind requested changes
В целом все очень не плохо) Но кое чего я бы поправил:

- useMountEffect c ignore выделить в кастомный хук (ну или текущий mountEffect допилить)
- кажется ном идее вытащить логику по ренлерингу сущности внутрь сущности с общим интерфейсом для всех типов render, что бы ваш view слой просто пробегал циклом и у всех вызывал render;
- логику со спрайтами думаю стоит выделить в отдельный класс;

2022-11-11 09:57 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +  let ignore = false;
Надо это выделить в отдельный хук, что бы каждый раз не писать штуку с ignore

2022-11-11 09:57 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +    game.current.init(ignore, () => {
Не надо передавать ignore в игру - это вообще не ее зона ответственности - эта логика должна быть снаружи:
```

  useMountEffect(() => {
    if (!ignore) {
      game.current = new Game(canvas.current as HTMLCanvasElement);
      game.current.init(() => {
        console.log('Игра загружена');
      });
      ignore = true;
    }

    return () => {
      game.current?.destruct();
      ignore = true;
    };
  });
```

2022-11-11 09:57 UTC, khitrind commented on packages/client/src/logic/Game/Game.tsx
> +    await Promise.all(sprites.map(sprite => sprite.load()));
Я бы вынес логику работы с спрайтами в отдельный класс

2022-11-11 09:57 UTC, khitrind commented on packages/client/src/logic/View.ts
> +  }
В идеале - это просто массив сущностей, который мы обходим и вызываем везде метод render. Как будто классу view не нада знать о том, что именно это за сущность. + почему метод render не в классе самого npc?

2022-11-11 09:57 UTC, khitrind commented on packages/client/src/logic/View.ts
> +  public ctx?: CanvasRenderingContext2D | null;
Я бы предложил избавиться от опциональности, если контекста нет - заканчивал бы игру - что логично.

const ctx = this.canvas.getContext('2d');

if (ctx === null) {
   game over
}
this.ctx = ctx;

2022-11-11 16:39 UTC, DianaIvanovna commented
Изменила структуру игры: 
Класс Game - корневой класс для инициализации всех доп компонентов
Класс View - отвечает за цикл рисования и вызывает отрисовку компонентов
Класс Player - передвижение игрока, отдает координаты + render себя
Класс NpcControll - хранит всех npc в массиве и вызывает render всех npc
Класс Npc - хранит свои координаты, спрайт, метод render
Класс AllSprites - хранит и делает загрузку всех спрайтов

PS: обработка столкновений пока в классе view, в след ПР усложню логику и вынесу в отдельный класс

так же сделала хук useMountEffectOneCall который вызывается 1 раз вместо 2

2022-11-14 13:23 UTC, khitrind approved these changes

2022-11-14 13:23 UTC, khitrind commented on packages/client/src/logic/Npc.ts
> +export class Npc {
Давай разнесем Npc и NpcControll на разные файлики, так проще будет их воспринимать

2022-11-14 13:36 UTC, user14052020 approved these changes

2022-11-14 14:53 UTC, merged