Pra 70: Затащить в проект i18n
yandex-team-01/middle.game.praktikum.yandex pull request #17
Opened 2022-11-12 13:29 UTC by samgxlden

Папка хранения переводов: ../client/public/locales

Модуль подключен в debug режиме, файл конфигурации i18next.config.ts

В конфиге закомментировано дополнение автоматического определения языка браузера, чтобы была возможность вручную переключать нужный язык

В дальнейшем необходимо рассмотреть возможность подключения кнопок для выбора языка или изменение языка через slug в url

2022-11-13 21:14 UTC, samgxlden commented
Добавил автоопределение языка браузера
Редирект на страницу с переводом выбранного языка
Возможность изменять перевод через slug в url
Добавил переводы для ошибок store

Не получилось устранить:
React ругается на переводы в store, пока что только текст в словарь добавил, код потом

2022-11-14 11:05 UTC, helgamir reviewed
Привет! Спасибо, что добавил i18n, здорово получилось.
я бы только поправила некоторые опечатки. И ещё сломались переходы по роутеру на форуме. Попробуй нажать "создать тему" или "назад" или кликнуть на любую тему. Выдаст 404.

2022-11-14 11:10 UTC, samgxlden commented on packages/client/src/App.tsx
> +  const { t } = useTranslation()
@helgamir это официальное название из документации, часто распространено

2022-11-14 11:11 UTC, samgxlden commented on packages/client/public/locales/ru/translation.json
> +  "homeDescription": "Основная цель игры - найти ключ и собрать алмазы. <br /> С помощью ключа вы можете открыть дверь, которая приведет вас на следующий уровень. В эту игру можно играть как одному,
@helgamir нет, какой был написан такой сделал

2022-11-14 11:14 UTC, helgamir commented on packages/client/public/locales/ru/translation.json
> +  "homeDescription": "Основная цель игры - найти ключ и собрать алмазы. <br /> С помощью ключа вы можете открыть дверь, которая приведет вас на следующий уровень. В эту игру можно играть как одному,
@samgxlden думаю лучше сразу текст, который подходит к нашей игре, если тебе не сложно. Мне кажется на демо важно, чтобы текст был уже про нашу игру.

2022-11-14 13:20 UTC, khitrind requested changes
В целом все супер, кроме те комментариев, которые я написал

2022-11-14 13:20 UTC, khitrind commented on packages/client/i18next.config.ts
> +    debug: true,
Это значение должно выставляться снаружи через process.env к примеру

2022-11-14 13:20 UTC, khitrind commented on packages/client/src/App.tsx
> +  }, [t])
Так никто не делает, этоткусочек либо на сервере генерят, либо просто выставляют на английском. Так что я бы просто подождал спринт с ssr

2022-11-14 13:20 UTC, khitrind commented on packages/client/src/components/Routing/Routing.tsx
> +        <Route path="/" element={<Navigate to={`/${lang}/`} replace />} />
Так, ну это супер мутная схема, так лучше не надо.

- значения может не быть в localStorage, что бы мы тогда выставляем?
- в целом зачем нам роутинг разделенный по языкам?

2022-11-14 13:20 UTC, khitrind commented on packages/client/src/pages/Forum/components/BlockCreateTopic/BlockCreateTopic.tsx
>  import { ITopic } from '../../part/Topic/types';
Давай все приведем к абсолютным путям

2022-11-14 13:25 UTC, samgxlden commented on packages/client/src/components/Routing/Routing.tsx
> +        <Route path="/" element={<Navigate to={`/${lang}/`} replace />} />
@khitrind у нас есть дефолтное значение языка
Также язык подбирается автоматически исходя от языка браузера, если такого нет, берется дефолтное
Дефолтное автоматически в этом случае добавляется в локарсторадж
То есть локарсторадж всегда есть, он кешируется всегда

Роутинг по языкам нужен во первых для удобства переключения языка, во вторых для SEO

2022-11-14 13:26 UTC, samgxlden commented on packages/client/i18next.config.ts
> +    debug: true,
@khitrind речь про дебаг?

2022-11-14 13:31 UTC, samgxlden commented on packages/client/src/components/Routing/Routing.tsx
> +        <Route path="/" element={<Navigate to={`/${lang}/`} replace />} />
@khitrind специально искал как сделать такое решение на примере сторонних библиотек
Так как знаю его ценность
Как лучше его реализовать?

2022-11-16 09:35 UTC, khitrind commented
@samgxlden Давай не будем строить космолет, а пойдем итеративным путем, в этом PR просто подключение либы (возможно начать использование), но без breaking changes в роутинге. Роутинг - это отдельная задача

2022-11-16 20:27 UTC, samgxlden commented on packages/client/src/pages/Forum/components/BlockCreateTopic/BlockCreateTopic.tsx
>  import { ITopic } from '../../part/Topic/types';
@khitrind для этого будет отдельная ветка

2022-11-16 20:29 UTC, samgxlden commented
@khitrind роутинг ведь не ломает проект и он вполне работает

2022-11-17 09:01 UTC, khitrind requested changes
Все выглядит не плохо - отличная работа, но давай добавим немного безопасности:

- обертка над localStorage, что-то в таком духе:
```


enum LocalStorageItems {
    Lang = 'i18Lang'
}

const LOCAL_STORAGE_DEFAULTS: Record<LocalStorageItems, string> = {
    [LocalStorageItems.Lang]: 'ru',
};

export function getLocalStorageItem(key: LocalStorageItems) {
    const res = localStorage.getItem(key);
    return res || LOCAL_STORAGE_DEFAULTS[key]
}
```

- так же хочется определить в одном месте лгику построения урла, что бы в каждом месте не строить это шаблонную строку

2022-11-17 14:47 UTC, khitrind commented on packages/client/i18next.config.ts
> +    debug: true,
+

2022-11-17 23:15 UTC, samgxlden commented on packages/client/src/components/Input/types.ts
> +  onChange?: (e: React.ChangeEvent) => void;
@khitrind почему инпуты и кнопки должны обязательно возвращать onClick или onChange? у нас нет прямых зависимостей, помимо требований в линтере
для чего мы вешаем это?

2022-11-18 10:14 UTC, khitrind commented on packages/client/src/components/Input/types.ts
> +  onChange?: (e: React.ChangeEvent) => void;
Потмоу что кнопка без обработчика - это что-то странное, кмк. Обычно делают onClick | href исключающие.
```

export type RequireOnlyOne<T, Keys extends keyof T = keyof T> =
  Pick<T, Exclude<keyof T, Keys>>
  & {
    [K in Keys]-?:
    Required<Pick<T, K>>
    & Partial<Record<Exclude<Keys, K>, undefined>>
  }[Keys]
  
  export type ButtonProps = RequireOnlyOne<Props, 'onClick' | 'href'> 
```

2022-11-18 10:16 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +  const handleBack = () => navigator('/');
Тут же ничего не поменялос, теперь просто бе useCallback.  Я имел в виду како-нибудь такое хелпер,

```
const useNavigate = (link: string) => {
  const navigator = useNavigator();

  const callback = useCallback(() => {
    navigator(link);
  }, [navigator]);

  return callback;
};
```

2022-11-18 10:17 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +  const handleBack = () => navigator('/');
Почему тут просто navigator, а не колбек?

2022-11-18 10:17 UTC, khitrind commented on packages/client/src/pages/Forum/part/Topic/Topic.tsx
> +    navigator('topic');
Тут тоже нет нового хука

2022-11-18 10:18 UTC, samgxlden commented on packages/client/src/components/Game/Game.tsx
> +  const handleBack = () => navigator('/');
@khitrind калбек внутри навигатора
Это кастомный хук

2022-11-18 10:18 UTC, khitrind approved these changes
Я апрувну, но надо исправить ситуацию с navigate, у тебя сейчас в одном этом PR 2 способо перейти на другую страницу. Давай сведем все к одному. И можно мерджить

2022-11-18 10:18 UTC, samgxlden commented on packages/client/src/pages/Forum/part/Topic/Topic.tsx
> +    navigator('topic');
@khitrind навигатор это новый хук

2022-11-18 21:42 UTC, merged