Pra 77 исправить замечания по 5 спринту
yandex-team-01/middle.game.praktikum.yandex pull request #18
Opened 2022-11-14 10:36 UTC by helgamir

Исправлены замечания указанные в спринте 5 https://github.com/yandex-team-01/middle.game.praktikum.yandex/pull/12
Кроме замечаний по игре и профайлу (отданы авторам).
При возможности нужно будет еще переделать стор по доке https://redux-toolkit.js.org/usage/usage-guide#using-selectors-with-createentityadapter
И вынести все селекторы на проект (сейчас часть дублируется прямо в компонентах).

2022-11-14 11:57 UTC, user14052020 approved these changes
выглядит как огромная работа) спасибо!

2022-11-14 13:28 UTC, khitrind requested changes
Выглядит отлично, но давай:

- вынесем селекторы к слайсам;
- обернем обработчики, который передаются в компоненты в useCallback;

2022-11-14 13:28 UTC, khitrind commented on packages/client/src/App.tsx
> +const selectAuth = createSelector(
Селекторы обычно живут рядом со sliceом

2022-11-14 13:28 UTC, khitrind commented on packages/client/src/components/ErrorsNotification/ErrorItem.tsx
>  import React from 'react';
```suggestion
import React, {memo} from 'react';
```

2022-11-14 13:28 UTC, khitrind commented on packages/client/src/components/ErrorsNotification/ErrorItem.tsx
> +export const ErrorItem = React.memo(({ text, id, closeHandler }: Props) => {
```suggestion
export const ErrorItem = memo(({ text, id, closeHandler }: Props) => {
```

2022-11-14 13:28 UTC, khitrind commented on packages/client/src/components/ErrorsNotification/ErrorsNotification.tsx
> +  const handleClose = useCallback(
useBoundAction

2022-11-14 13:28 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +          }}>
Функция передается в компонент, давай обернем обработчик в useCallback

2022-11-14 13:28 UTC, khitrind commented on packages/client/src/pages/Landing/Landing.tsx
> +  const navigateLogin = () => {
useCallback

2022-11-14 13:29 UTC, khitrind commented on packages/client/src/store/forum/initialSlice.ts
> +    console.log('++', acc);
Это кажется отладочный код

2022-11-14 21:53 UTC, helgamir commented on packages/client/src/store/auth/AuthActions.ts
> +      return await fetchApi('/auth/user', {});
@khitrind кажется ссылка не прикрепилась?

2022-11-15 13:32 UTC, khitrind approved these changes

2022-11-15 13:32 UTC, khitrind commented on packages/client/src/components/ErrorsNotification/ErrorsNotification.tsx
> +  });
```suggestion
  const handleClose = useBoundAction((id: string) => removeError(id));
```

2022-11-15 14:05 UTC, helgamir commented on packages/client/src/pages/LoginPage/LoginForm.tsx
> +                  console.log('submit');
это заглушка функции. api пока не сделан же, а кнопка требует, и eslint требует

2022-11-15 14:39 UTC, merged