Pra 66: api изменения данных пользователя
yandex-team-01/middle.game.praktikum.yandex pull request #22
Opened 2022-11-16 17:43 UTC by samgxlden

pra-19-раздел-со-сменои-пароля
https://linear.app/teamproject/issue/PRA-19/razdel-so-smenoj-parolya
pra-20-api-для-смены-пароля
https://linear.app/teamproject/issue/PRA-20/api-dlya-smeny-parolya
pra-66-api-изменения-данных-пользователя
https://linear.app/teamproject/issue/PRA-66/api-izmeneniya-dannyh-polzovatelya

Для валидации полей задействована библиотека formik

**Добавить потом:**
Компонент с аватаркой и api смены аватара настрою в следующей ветке

2022-11-17 09:53 UTC, khitrind requested changes
В комментах опсиал подробно что хотелось бы поправить

2022-11-17 09:53 UTC, khitrind commented on packages/client/src/components/Form/Form.tsx
> +import { ErrorBoundary } from '../ErrorBoundary';
Вроде везде абсолютные пути

2022-11-17 09:53 UTC, khitrind commented on packages/client/src/components/Input/Input.tsx
> +  placeholder,
Тут бы лучше сделать дефолт пустой строкой

2022-11-17 09:53 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsChangeData/SettingsChangeData.tsx
> +  useEffect(() => {
useMountEffect

2022-11-17 09:53 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsChangeData/SettingsChangeData.tsx
> +      });
вся эта лгика должна лежать в экшене, если нужно выполнить что-то после - либо передаем колбеком, либо в данном случае нужно кусок роутера в редаксовский контекст положить. Писать всю логику так в компонент плохая практика

2022-11-17 09:53 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsChangeData/SettingsChangeData.tsx
> +  const phone = user.user?.phone;
Этот кусок тоже выглядит очень странно. По логикуе происходящего, если нет юзера, значит этот компонент вообще не должен отрисовыватьcя.

получается, что эта страница должны быть доступна только для залогина. Так же в самом верху првоерка на наличие юзера. Если юзера нет вернуть null или редиректить на `/ `, так как с нашей точки зрения - это невозможная ситуация, что человек без пользователя смог зайти на эту страницу. И это поможет избавиться от опциональности и не писать везде ?.

2022-11-17 09:53 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsChangePassword/SettingsChangePassword.tsx
> +      .then((res) => {res ? goBackHandle() : null});
Точно те же комменты что и к SettingsChangeData

2022-11-17 09:53 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsUserInfo/SettingsUserInfo.tsx
> +  useEffect(() => {
useMountEffect

2022-11-17 09:53 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsUserInfo/SettingsUserInfo.tsx
> +
та же проблема, что и выше

2022-11-17 10:32 UTC, DianaIvanovna commented on packages/client/src/constants/Schemas.ts
У формика есть функция проверки почты email(), почему не воспользоваться ей ?
Залезла сейчас в их код и там такое регулярное выражение 
```
let rEmail = /^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))$/i;
```

2022-11-17 10:52 UTC, DianaIvanovna commented on packages/client/src/pages/SettingsPage/components/SettingsChangeData/SettingsChangeData.tsx
> +  }, [dispatch]);
запрос на авторизацию сделан в файле App. Далее если пользователь не авторизован , то мы ему должны запретить находится на странице settings. 


```
 <Route
          path="/settings"
          element={
            <ProtectedRoute flag={auth} redirect="/login">
              <BackgroundLayout>
                <SettingsPage />
              </BackgroundLayout>
            </ProtectedRoute>
          }>
          <Route index element={<SettingsData />} />
          <Route path="edit" element={<SettingsChangeData />} />
          <Route path="password" element={<SettingsChangePassword />} />
        </Route>
```

с другой стороны, он может быть сначала неавторизован, а после зарегистрироваться в сервисе. В Api регистрации от яндекса нам не возвращаются данные пользователя. 

Можно пойти 2 путями, после успешных запросов /auth/signin и /auth/signup запрашивать данные пользователя методом /auth/user

Или только в файле SettingsPage.tsx добавить следующую логику: 

```
export const SettingsPage = () => {
  const user = useAppSelector(state => state.auth.user);
  const dispatch = useAppDispatch();

  useEffect(() => {
    if (!user) {
      dispatch(fetchAuth());
    }
  }, [dispatch, user]);

  if (!user) {
    return <Spinner />;
  }

  return (
    <BlankWindow>
      <Outlet />
    </BlankWindow>
  );
};
```

2022-11-17 11:04 UTC, DianaIvanovna commented on packages/client/src/pages/SettingsPage/components/SettingsChangeData/SettingsChangeData.tsx
> +  const phone = user.user?.phone;
К сожалению Дмитрий, так не получится сделать. [Api регистрации](https://ya-praktikum.tech/api/v2/swagger/#/Users/put_user_profile) яндекса сделано так, что при регистрации запрашиваются все данные, кроме display_name. 

А при обновление данных display_name обязательное поле. Т е у нового зарегистрированного человека данного поля не будет и на него нужно сделать проверку

Можно сделать так 
```
const initialValues = {
...user, 
user.display_name || ""
}
```

2022-11-17 11:09 UTC, DianaIvanovna commented on packages/client/src/pages/SettingsPage/components/SettingsChangeData/SettingsChangeData.tsx
> +          value={values.email}
не очень понимаю, зачем делать placeholder, если ты в initialValues передаешь те же данные и placeholder не покажется.

placeholder  нужен когда в input нет значения, например "введите почту" но у нас есть заголовок и благодаря нему понятно, что нужно вводить. 

Мне кажется placeholder   лишний

2022-11-17 11:16 UTC, DianaIvanovna commented on packages/client/src/store/types.ts
> +
ChangeDataState нигде не используется

2022-11-17 11:20 UTC, DianaIvanovna commented on packages/client/src/store/users/UsersSlice.ts
> +  loading: false,
зачем в usersSlice повторять данные checkAuth и  auth? 
Мне кажется лишним. При смене пароля и данных пользователя значения checkAuth и  auth не меняются

2022-11-17 11:21 UTC, DianaIvanovna commented on packages/client/src/store/users/UsersSlice.ts
> +import { IUser } from 'src/modules/IUser';
У тебя eslint не показывает ошибки? 
![image](https://user-images.githubusercontent.com/60156828/202433148-70bcaee6-3ae5-4120-9c3c-2cc98e04d8b6.png)

2022-11-18 08:45 UTC, DianaIvanovna commented on packages/client/src/pages/SettingsPage/components/SettingsChangeData/SettingsChangeData.tsx
> +      });
Зачем после изменения данных пользователя делать запрос fetchAuth? в ответе на запрос придет новый объект пользователя, его нужно просто обновить с store

2022-11-19 12:58 UTC, Victoriya0993 reviewed
Очень не хватает кнопки "Назад" со страницы профиля, чтобы вернуться на стартовую страницу

2022-11-21 21:05 UTC, samgxlden commented on packages/client/src/pages/SettingsPage/components/SettingsChangeData/SettingsChangeData.tsx
> +  const phone = user.user?.phone;
@DianaIvanovna вариант Димы сработал

2022-11-22 13:41 UTC, DianaIvanovna reviewed
Если сделать logout а потом зарегистрировать или войти как другой пользователь, то в профиле остаются данные старого пользователя. 

Нужно при logout очищать стейт данных пользователя, и при авторизации и регистрации отправлять запрос на получение данных нового  пользователя. 
Но это скорей моя недоработка, вынесу ее в отдельную задачу и решу после принятия твоего ПР

2022-11-22 13:56 UTC, DianaIvanovna reviewed
Еще меня беспокоит большое количество предупреждений и lint. Это происходит, потому что yarn lint смотрит собранный бандл и в нем 300+ ошибок. 
Можешь в .eslintrc.js добавить исключение для папки dist и исправить 5 предупреждениq eslint? 
```
"ignorePatterns": ["**/*.test.*", "**/*.config.*", "**/dist"]
```

2022-11-22 13:57 UTC, DianaIvanovna reviewed
В остальном все здорово, спасибо за введенный функционал !

2022-11-22 13:58 UTC, DianaIvanovna approved these changes

2022-11-22 19:40 UTC, merged