pra-16-функционал-авторизации
yandex-team-01/middle.game.praktikum.yandex pull request #3
Opened 2022-10-31 21:12 UTC by DianaIvanovna

### Какую задачу решаем
[PRA-16](https://linear.app/teamproject/issue/PRA-16/funkcional-avtorizacii) - функционал авторизации. 

Для этого добавила библиотеку @reduxjs/toolkit.
Асинхронные запросы выполнены с помощью createAsyncThunk в папке controllers. 

Дополнительно сделано: 
1.  Компонент ошибки - PopupError. Чтобы задиспачить ошибку нужно dispatch(setError(error.message)
Например ошибка запроса авторизации:
```
export const fetchAuth = createAsyncThunk(
  'auth/fetchAuth',
  async (_, thunkApi) => {
    try {
      const res = await fetchApi('/user', {})
      return res
    } catch (error) {
      const { setError } = errorSlice.actions

      if (error instanceof Error) {
        thunkApi.dispatch(setError(error.message))
      } else {
        thunkApi.dispatch(setError(`Какая-то ошибка в fetchAuth`))
      }
      return thunkApi.rejectWithValue(`Какая-то ошибка в fetchAuth`)
    }
  }
)
```

![image](https://user-images.githubusercontent.com/60156828/199109463-5a81c66a-70ff-4842-8a8b-f34a549ffc79.png)

2. Защищенный роут ProtectedRoute. Параметры flag - условие показа страницы redirect - путь для редиректа

В данный момент нельзя попасть на главную страницу и страницу форума, если пользователь не авторизован, будет редирект на страницу login
Пример:
```
<Route
          path="/"
          element={
            <ProtectedRoute flag={auth} redirect="/login">
              <BackgroundLayout>
                <div>Вот тут будет жить ваше приложение :)</div>
              </BackgroundLayout>
            </ProtectedRoute>
          }
 />
```

2022-11-01 07:54 UTC, khitrind requested changes
Привет, в целом выглядит оч не плохо, по коду написал пару комменатриев, что мне кажется можно сделать чуть проще, а что чуть сложнее)

Ищ основного:

- давай переделаем ErrorPopup на очередь ошибок [видосик](https://www.youtube.com/watch?v=kkA_iMkSJDk);
- добавим eslint праило про экспорты, что бы это не было предметом разговоров на ревью;

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/App.tsx
> +  // useEffect(() => {
Если этот код не нужен лучше бы его удалить

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/App.tsx
> +      </Routes>
Весь роутинг можно вынести в компонент с названием routing, и в аппе оставить только:
   ```
 <>
      <PopupError />
      <Routin />
    </>
```

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/components/Input/types.ts
> +  error?: string
Тут бы еше наследование от InputHTMLAttributes убрать)

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/components/Input/types.ts
> +  error?: string
И any кажется так же лишним `React.ChangeEvent<any>`

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/components/PopupError/PopupError.tsx
> +export const PopupError = (): JSX.Element | null => {
```suggestion
export const PopupError = () => {
```

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/components/PopupError/PopupError.tsx
> +  }, [error])
В целом рабочий вариант, но не понгятно как это будет работать, если придет к примеру 5 ошибок одновременно. Я бы предложил перейти на работу с очередью сообщений

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/components/PopupError/index.ts
> +export default PopupError
[Именованный экспрорт](https://eslint.org/docs/latest/rules/no-restricted-exports)

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/components/Preloader/Preloader.tsx
> +export const Preloader = (): JSX.Element => {
```suggestion
export const Preloader = () => {
```

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/constants/Schemas.ts
> +//import * as Yup from 'yup'
Не забывай пожалуйста удалять закоменченный код

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/controllers/AuthController.ts
> +      return thunkApi.rejectWithValue(`Какая-то ошибка в fetchAuth`)
Для чего вся эта логика? и как ошибка в catch. может быть не instanceoof Error?

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/controllers/AuthController.ts
> +import { fetchApi } from './utils'
Почему fetchApi в utils?)

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/controllers/AuthController.ts
> +import { createAsyncThunk } from '@reduxjs/toolkit'
/controllers/AuthController - это же как-будто не контроллер, а просто набор экшенов их можно просто положить в store/auth/actions.ts

В целом сторое часто удобно делать по доменам папка auth - в ней лежит authSlice и actions к примеру

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/controllers/utils.ts
> +  let status: number
Для чего тут status через let?

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/controllers/utils.ts
> +  return fetch(`${baseUrl}${path}`, {
Можно несколько проще:

```
export const fetchApi = <T,>(path: string, options: RequestInit): Promise<T> => {
  return fetch(`${baseUrl}${path}`, {
    ...options,
    credentials: 'include',
  })
    .then(res => {

      if (res.status < 200 || res.status > 299) {
        return Promise.reject(new Error(res.reason))
      }
      const contentType = res.headers.get('content-type')

      if (contentType && contentType.indexOf('application/json') !== -1) {
        return res.json()
      }

      return res.text()
    });
}

```

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/pages/Forum/components/CreateTopic/CreateTopic.tsx
>  const CreateTopic = (props: any) => {
Почему тут any?)

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +  }, [auth])
Это стоит решать через такой же редирект снаружи а не через useEffect

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/pages/RegistrationPage/RegistrationPage.tsx
> +  useEffect(() => {
Редирект

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/pages/RegistrationPage/RegistrationPage.tsx
>    const { values, errors, touched, handleChange, handleSubmit, handleBlur } =
Я бы предлодил вынести всб логику про форму из компонента страницы. Страница -это страница, форма - это форма

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/store/slices/ErrorSlice.ts
> +export default errorSlice.reducer
```suggestion
export const { reducer } = errorSlice;
export const { setError } = errorSlice.actions;

```

2022-11-01 07:54 UTC, khitrind commented on packages/client/src/store/store.ts
> +// import errorReducer from './slices/ErrorSlice'
.

2022-11-01 14:07 UTC, DianaIvanovna commented on packages/client/src/controllers/AuthController.ts
> +      return thunkApi.rejectWithValue(`Какая-то ошибка в fetchAuth`)
как я понимаю, в  TypeScript catch имеют только тип unknown
![image](https://user-images.githubusercontent.com/60156828/199252079-8763df27-b1e7-413c-88ee-03850d201bc0.png)

я пыталась убрать ошибку разными способами, но получилось только так
![image](https://user-images.githubusercontent.com/60156828/199252610-3d67480a-aa05-4d1d-8a9e-f0f9ce3b1c73.png)

![image](https://user-images.githubusercontent.com/60156828/199252694-e6790388-a98c-442e-ba81-cc75f5c1b8ae.png)

2022-11-01 14:08 UTC, DianaIvanovna commented on packages/client/src/controllers/AuthController.ts
> +import { fetchApi } from './utils'
вынесла в папку utils чтобы потом данный fetch мог применяться в AuthController, UserController и т д. Куда лучше вынести ?

2022-11-01 14:14 UTC, DianaIvanovna commented on packages/client/src/controllers/AuthController.ts
> +import { createAsyncThunk } from '@reduxjs/toolkit'
согласна, так и сделаю

2022-11-01 14:22 UTC, DianaIvanovna commented on packages/client/src/controllers/utils.ts
> +  let status: number
мне пришло это сделать потому что api яндекса возвращает в ответе статус 401 и текст ошибки. 
 
1. Если я буду вызывать ошибку в первом then, я не смогу вытащить текст ошибки
![image](https://user-images.githubusercontent.com/60156828/199254994-995c834f-dff7-4ec6-885e-96d75b25404a.png)
![image](https://user-images.githubusercontent.com/60156828/199255101-099395e2-04c4-4b71-9b87-0b2172a05351.png)

2. Чтобы вытащить текст ошибки, мне нужно сделать res.text() и во втором then проверить статус запроса и вызвать ошибку. Если я не буду проверять статус запроса во втором then, то redux посчитает запрос fulfilled. Чтобы проверить статус запроса во втором then, пришлось сохранить его в переменную

2022-11-01 14:25 UTC, DianaIvanovna commented on packages/client/src/controllers/utils.ts
> +  return fetch(`${baseUrl}${path}`, {
если я сделаю так, то не смогу вытащить текст ошибки и показать пользователю, что именно пошло не так. Не правильные куки или логин или паспорт неправильный

2022-11-01 14:25 UTC, DianaIvanovna commented on packages/client/src/pages/Forum/components/CreateTopic/CreateTopic.tsx
>  const CreateTopic = (props: any) => {
это код Виктории и думаю она сделала это специально, т к еще не спроектировала в каком формате будут приходить данные.

2022-11-01 14:29 UTC, DianaIvanovna commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +  }, [auth])
Я сделала так, чтобы когда пользователь на странице login авторизовался, то его бы перебрасывала на главную страницу. 

auth у меня показывает, что пользователь авторизован. Если я сделаю такой редирект в App компоненте, то авторизованный пользователь будет вечно при перезагрузке страницы попадать на страницу "/"

Как тогда лучше сделать?

2022-11-01 14:30 UTC, DianaIvanovna commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +  }, [auth])
а я поняла, что вы имели в виду. вот так ?

```
  if (auth) {
    return <Navigate to="/" />
  }
```

2022-11-01 14:33 UTC, DianaIvanovna commented on packages/client/src/pages/RegistrationPage/RegistrationPage.tsx
>    const { values, errors, touched, handleChange, handleSubmit, handleBlur } =
данная страница состоит только из формы. Все равно вынести? Просто в RegistrationPage создать папку modules и там RegForm и весь код туда ?

2022-11-01 21:15 UTC, khitrind commented on packages/client/src/pages/RegistrationPage/RegistrationPage.tsx
>    const { values, errors, touched, handleChange, handleSubmit, handleBlur } =
Сейчас только из формы - но логически это разные сущности, так что лучше в отдельный компонент, RegistrationForm

2022-11-01 21:23 UTC, khitrind commented on packages/client/src/controllers/AuthController.ts
> +      return thunkApi.rejectWithValue(`Какая-то ошибка в fetchAuth`)
Я посмотрю как это можно сделать, но в данном кейсе - это не важно от слова совсем( Мы же не хотим пользователю показывать какую-то техническую информацию. В данном случае достаточно:
```

export const fetchAuth = createAsyncThunk(
  'auth/fetchAuth',
  async (_, thunkApi) => {
    try {
      const res = await fetchApi('/user', {})
      return res
    } catch (error) {
      const { setError } = errorSlice.actions
      thunkApi.dispatch(setError('Ошибка авотризации попробуйте еще раз'))
    }
  }
)
```

2022-11-01 21:28 UTC, khitrind commented on packages/client/src/controllers/AuthController.ts
> +      return thunkApi.rejectWithValue(`Какая-то ошибка в fetchAuth`)
Но есть вариант, что это не возможно( https://kentcdodds.com/blog/using-fetch-with-type-script#typing-the-rejected-value-of-the-promise

2022-11-01 21:29 UTC, khitrind commented on packages/client/src/controllers/AuthController.ts
> +import { fetchApi } from './utils'
А не очень понятно, зачем нужны контроллеры, есть условно сетевой слой который умеет сходить в сеть и попарсить данные, его можно просто в папку api убрать. А есть слой данных, где мы дергаем метод в экшене и кладем в стор

2022-11-01 21:34 UTC, khitrind commented on packages/client/src/controllers/utils.ts
> +  let status: number
Тут просто логика поломанная получается. Мы в 2 местах проверяем на наличие ошибок - сразу в первом then надо проверить и статус и ok и если что-то пошло не так бросить reject (и либо как-то его кастомно обработать в соледующем catch либо нам просто важен факт ошибки и тогда просто прокидываем его дальше).

2022-11-01 21:35 UTC, khitrind commented on packages/client/src/controllers/utils.ts
> +  return fetch(`${baseUrl}${path}`, {
Почему? Что мешает сделать это в catch блоке?

2022-11-02 14:05 UTC, khitrind requested changes
Привет, спасибо за правки, оставил еще пару и еще, добавь пожалуйста yarn-error.log в gitignore. А то у тебя на PR 9к строк изменений_

2022-11-02 14:05 UTC, khitrind commented on packages/client/src/pages/Forum/Forum.tsx
> +// import Button from './components/Button/Button';
Стоит удалить закоменченный код

2022-11-02 14:05 UTC, khitrind commented on packages/client/src/pages/LoginPage/LoginPage.tsx
> +  }, [auth])
Нет, оберунть login в protectedRout и проверять там залогированность. Если есть auth, то редирект на `/`. В целом задача - вынести логику редиректа из страницы. СТраница максимально глупая, она не должна внутри себя что-то проверять

2022-11-03 09:49 UTC, khitrind requested changes
В целом гораздо лучше, давай разберемся с yarn-error.log и можно коммититт

2022-11-03 09:49 UTC, khitrind commented on .gitignore
> +yarn-error.log*
Без звездочки, он не добавлялся в gitignore

2022-11-03 10:28 UTC, khitrind approved these changes

2022-11-03 11:58 UTC, Helga108 approved these changes
Огромная работа проделана! Супер!
я там незначительные комменты/вопросы написала. Можем решить уже не в этом pr. Аппрувлю.

2022-11-03 11:58 UTC, Helga108 commented on packages/client/src/store/utils.ts
> +export const fetchApi = (path: string, options: RequestInit): Promise<any> => {
мы axios решили не брать?

2022-11-03 11:58 UTC, Helga108 commented on packages/client/src/components/Preloader/Preloader.tsx
> +export const Preloader = () => {
Не надо ли их объединить со Spinner'ом который я делала в предыдущих pr? вроде они дублируют друг друга

2022-11-03 11:58 UTC, Helga108 commented on packages/client/src/components/ErrorsNotification/ErrorItem.tsx
> +      <svg
Ты вроде говорила выносить в отдельный файл svg? может так и сделаем?

2022-11-03 12:11 UTC, merged