Pra 22: api для работы с аватаркои
yandex-team-01/middle.game.praktikum.yandex pull request #30
Opened 2022-11-23 23:49 UTC by samgxlden

API для работы с аватаркой, без оформления и рефакторинга компонента аватара
Оформление и рефакторинг аватара в следующем PR

2022-11-24 12:11 UTC, helgamir reviewed
написала некоторые комменты, поправь, пожалуйста.
Еще у тебя почему-то линтер пропускает any, хотя у нас настроено, чтобы не пропускал никогда. Проверь, пожалуйста, у себя настройки. И что precommit hook не пропускается.

2022-11-24 12:11 UTC, helgamir commented on packages/client/src/pages/SettingsPage/components/SettingsAvatar/SettingsAvatar.tsx
> +  const user = useAppSelector(state => state.auth.user as IUser);
У нас селекторы вынесены отдельно. Используй, пожалуйста, те что там, или создай свой в том же файле.

2022-11-24 12:11 UTC, helgamir commented on packages/client/src/pages/SettingsPage/components/SettingsAvatar/SettingsAvatar.tsx
> +  const uploadAvatar = (event: any) => {
у нас же на any стоит полный запрет вроде. Интересно, как линтер это пропустил.. Давай типизируем, пожалуйста.

2022-11-24 12:11 UTC, helgamir commented on packages/client/src/pages/SettingsPage/components/SettingsAvatar/SettingsAvatar.tsx
> +    const file = event.target.files[0]
мне кажется тут надо типизировать, и/или добавить проверку на то, что файлы там вообще есть. Иначе все упадёт с ошибкой, если вдруг что-то пойдет не так.

2022-11-24 12:11 UTC, helgamir commented on packages/client/src/store/users/UsersActions.ts
> +  async (data: any, thunkApi) => {
точно any? мы договорились нигде не использовать вроде

2022-11-24 12:57 UTC, helgamir commented on packages/client/src/pages/SettingsPage/components/SettingsAvatar/SettingsAvatar.tsx
> +    const file = event.target.files[0]
тут еще можно переименовать uploadAvatar на onAvatarUpload, т.к. это событие, события принятно с "on" именовать вроде бы.

2022-11-24 18:05 UTC, khitrind requested changes
Давайте разбираться с any

2022-11-24 18:05 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsAvatar/SettingsAvatar.module.scss
> +}
EOF

2022-11-24 18:05 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsAvatar/SettingsAvatar.tsx
>  import img from 'src/assets/images/no-avatar.png';
Просто img не очень хорошее название, не говорящее ни о чем. Тут бы лучше подошло. emptyAvatr к пример

2022-11-24 18:05 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsAvatar/SettingsAvatar.tsx
> +  const url = `${env.HOST_RESOURCES}${user.avatar}`;
Построение url стоит вынести в отдельную функцию, и использовать ее везде, что бы был единый источник правды

2022-11-25 09:03 UTC, helgamir reviewed
Спасибо, всё типизировал, отлично!
Еще чуть-чуть поправить и разобраться с prettier, и всё будет супер.

2022-11-25 09:03 UTC, helgamir commented on packages/client/src/store/auth/AuthSelectors.ts
> +    auth => auth.user as IUser
еще у тебя этот блок уехал по сравнению с остальными. Начни, пожалуйста, использовать prettier на сохранение. Не будет ни EOF, ни вот таких вот случайных отъездов блоков.
Если нужна помощь с настройкой, обращайся.

![image](https://user-images.githubusercontent.com/4964091/203941315-e099243d-3819-45ed-a5ca-4a6b9a6432ce.png)

2022-11-25 10:38 UTC, khitrind approved these changes
Давай уберем as и можно мерджить

2022-11-25 10:38 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsAvatar/SettingsAvatar.tsx
> +    const file: File = (target.files as FileList)[0];
Тут бы добавить проверку, что файл действительно существует

2022-11-25 10:38 UTC, khitrind commented on packages/client/src/store/auth/AuthSelectors.ts
> +    auth => auth.user as IUser
AS тут не нужен совсем - в данном месте тип сам должен выводиться из стейта

2022-11-26 12:10 UTC, samgxlden commented on packages/client/src/store/auth/AuthSelectors.ts
> +    auth => auth.user as IUser
Без этого TS валится

2022-11-26 12:12 UTC, samgxlden commented on packages/client/src/store/auth/AuthSelectors.ts
> +    auth => auth.user as IUser
> тут юзера не надо типизировать. он уже типизирован в рут стейте. Если посмотришь на тип в ide, там он уже будет.

Без этого TS валится. user опирается на auth
у нас приложение только для авторизованных пользователей, по отношению к этой странице это точно так
нет смысла проверять проверку проверки, лучшего способа, пока что не нашли

2022-11-26 12:22 UTC, samgxlden commented on packages/client/src/store/auth/AuthSelectors.ts
> +    auth => auth.user as IUser
У нас user по умолчанию null, чтобы обнулять его стейт до пустого состояния после logout

2022-11-26 13:00 UTC, DianaIvanovna approved these changes

2022-11-26 16:22 UTC, merged