Pra 25 реализовать api лидерборда
yandex-team-01/middle.game.praktikum.yandex pull request #39
Opened 2022-12-08 12:24 UTC by helgamir

При окончании игры имя пользователя и его очки записываются через api яндекса в базу.
При заходе на лидерборд данные забираются из базы и отображаются.

2022-12-08 12:40 UTC, user14052020 approved these changes
все круто)мы на еще один шаг ближе к финалу)

2022-12-08 12:40 UTC, user14052020 commented on packages/client/src/constants/LeaderboardConsts.ts
> +export const SCORE_FIELD_NAME = 'huggywuggyscore';
```suggestion
export const SCORE_FIELD_NAME = 'huggywuggyscore';
```
```suggestion
export const SCORE_FIELD_NAME = 'huggy_wuggy_score';
```
чтобы было одинаково с team_01

2022-12-08 14:24 UTC, khitrind commented on packages/client/src/store/leaderboard/LeaderboardActions.ts
> +      const res = await fetchApi('/leaderboard', {
res unknoden, стоит передать тип возвращаемого значения в fetch 
```suggestion
      const res = await fetchApi<TypeForResponce>('/leaderboard', {
```

2022-12-08 14:33 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +  );
Это все useBoundAction

2022-12-08 14:34 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +          ratingFieldName: SCORE_FIELD_NAME,
Все вот эти SCORE_FIELD_NAME, TEAM_NAME и SCORE_FIELD_NAME. Должнеы формироваться в функции которая делает api запрос ну или на крайний случай в экшене - но точне не в компоненте.

Все что тут должно быть -` dispatch(sendrecord(score))`

2022-12-08 14:36 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +          ratingFieldName: SCORE_FIELD_NAME,
Даже юзер тут не нужен, он будет в контексте у экшена в стейте. Внутри санка можно сделать:

`thunkApi.getState().user;`

2022-12-08 14:37 UTC, khitrind commented on packages/client/src/hocs/withAuth.tsx
> +      dispatch(fetchAuth());
useBoundAction

2022-12-08 14:37 UTC, khitrind commented on packages/client/src/logic/Game.ts
> +    this.onEndGame = () => console.log('game ended');
Зачем так? Поле лучше просто сделать опциональным

2022-12-08 14:38 UTC, khitrind commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +  };
Если это что-то неизменяемое/конфиг зачем каждый раз объявлять в нутри компоненте? лучше вынести в константу на уровень модуля

2022-12-08 14:38 UTC, khitrind commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +    dispatch(getAllLeaderboard(requestData));
useBoundAction

2022-12-08 14:39 UTC, khitrind commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +              <th>Score</th>
i18n

2022-12-08 14:39 UTC, khitrind commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +          <table className={styles.table}>
А зачем тут верстка на таблицах?) Как будто такое уже давно не делают

2022-12-08 14:39 UTC, khitrind commented on packages/client/src/pages/Leaderboard/Leaderboard.tsx
> +          <table className={styles.table}>
Проще через grid (как раз потренироваться)

2022-12-08 14:40 UTC, khitrind commented on packages/client/src/pages/Leaderboard/components/LeaderboardLine.tsx
> +      </tr>
то же самое, давай на grid переделаем

2022-12-08 14:41 UTC, khitrind commented on packages/client/src/store/leaderboard/LeaderboardSlice.ts
> +      state.leaderboard = action.payload as [];
вот тут давай без as, в telegram написал как типизировать)

2022-12-08 14:41 UTC, khitrind commented on packages/client/src/store/leaderboard/LeaderboardSlice.ts
> +  leaderboard: [];
Это массив чего?

2022-12-08 14:42 UTC, khitrind commented on packages/client/src/store/leaderboard/LeaderboardSlice.ts
> +interface ILeaderBoardState {
Почему где-то тип описывается в файле со слайсом где-то в отдельном? Давайте прийдем к какому-то соглашению)

2022-12-08 14:44 UTC, khitrind commented on packages/client/src/store/leaderboard/LeaderboardActions.ts
> +      });
Мне кажется с запросами к api как будто не хватает еще одного слоя абстракции. Вот есть к примеру ваш fetchApi - это аналог HTTPTransport с первого модуля. просто штука которая ходит в сеть. Но должен быть еще apiService, который формирует данные для запроса и парсит ответ. В экшене мы просто дергаем эту функцию и перекладываем ответ в store. Так как будто логичнее и не будет мешанины и вопросов а что где делать)

2022-12-09 16:26 UTC, khitrind requested changes

2022-12-09 16:26 UTC, khitrind commented on packages/client/src/api/leaderboardApi.ts
> +const extData = (score: number, login: string | undefined) => {
Что такое extData?) Давай придумаем что более понятное, к примеру prepareLeaderboardRequestData, который возвращает объектик типа LeaderBoardRequestParams  (такой тип тоже стоит завести)

2022-12-09 16:26 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +  });
Ну нет же, в useBoundAction есть пример, как его использовать...

`const onEndGame = useBoundAction((score: number) => (recordScore(score));`

2022-12-09 16:26 UTC, khitrind commented on packages/client/src/store/leaderboard/LeaderboardActions.ts
> +    return getLeaderboard(data);
Тут хорошо бы тоже сделать await результату, у меня есть подозрение, что в таком виде try {} catch не сработает

2022-12-09 16:26 UTC, khitrind commented on packages/client/src/store/leaderboard/LeaderboardSelectors.ts
> +  leaderboard => leaderboard.isLoading
```suggestion
const selectLeaderboard = createSelector((state: RootState) => state.leaderboard);

export const selectLoading = createSelector(
  selectLeaderboard,
  leaderboard => leaderboard.isLoading
```

2022-12-09 20:35 UTC, khitrind approved these changes
Супер) но:

- давай запускать код перед посылкой на ревью;
- надо поправить `onEndGame` (в комментах описал как именно)

2022-12-09 20:35 UTC, khitrind commented on packages/client/src/api/leaderboardApi.ts
> +  return await fetchApi<Leader[]>('/leaderboard', {
```suggestion
export const addLeader = (score: number, login = '') => {
  return fetchApi<Leader[]>('/leaderboard', {
```

Так как мы тут ничего не ждем - это просто функция возвращающая промис, тут не нужен не async не await

2022-12-09 20:35 UTC, khitrind commented on packages/client/src/api/leaderboardApi.ts
> +  const res = await fetchApi<Leader[]>('/leaderboard/all', {
Тут точно такая же история

2022-12-09 20:35 UTC, khitrind commented on packages/client/src/components/Game/Game.tsx
> +    recordScore(score);
Ну так совсем не ок перед ревью хорошо бы запускать код. Это работать не будет, что бы заработало тут нежен `return`.  Ну я же не eslintом тут работаю(

2022-12-09 20:35 UTC, khitrind commented on packages/client/src/store/leaderboard/LeaderboardActions.ts
> +    return await addLeader(score, login);
Тут как будто модно сразу выводить ошибку, если не будет юзера

2022-12-09 20:35 UTC, khitrind commented on packages/client/src/store/leaderboard/LeaderboardActions.ts
> +    return await addLeader(score, login);
Потому что если его нет, запрос так и так упадет

2022-12-10 15:45 UTC, merged