pra-28-экран-или-страница-начала-игры
yandex-team-01/middle.game.praktikum.yandex pull request #4
Opened 2022-11-01 13:28 UTC by Helga108

Добавила экран для загрузки игры.

Для целей тестирования он открыватеся по роуту /loading Когда интегрируем с игрой, надо будет этот роут убрать.
Сейчас используется Interval, для того чтобы progress bar живой был. Если в игре будет какой-то вариант прикрутить к реальном процессу, сделаем, пропсы для этого есть.

Если у кого есть идеи, как использовать scss variables прям внутри компонента, сообщите. я не нашла рабочего способа, без использования каких-то костылей.

Также поправлены следующие баги верстки:
- при растягивании затенение бэкграунда теперь тоже растягивается (в body добавлено position:relative).
- исправлена опечатка в variables (и в компоненте)

![Screenshot at Nov 01 14-16-31](https://user-images.githubusercontent.com/4964091/199244352-15dd0ada-a7a9-46f1-8595-fc318bc37a29.png)

2022-11-01 21:48 UTC, khitrind requested changes

2022-11-01 21:48 UTC, khitrind commented on packages/client/src/components/ProgressBar/ProgressBar.tsx
> +  const { bgcolor, completed } = props
```suggestion
export const ProgressBar = ({ bgcolor, completed }: BarProps) => {
```

2022-11-01 21:48 UTC, khitrind commented on packages/client/src/components/ProgressBar/index.tsx
> +export default ProgressBar
```suggestion
export { ProgressBar } from './ProgressBar'
```

2022-11-01 21:48 UTC, khitrind commented on packages/client/src/components/Spinner/index.tsx
> +export default Spinner
```suggestion
export { Spinner } from './Spinner'
```

2022-11-01 21:48 UTC, khitrind commented on packages/client/src/pages/GameLoadingPage/GameLoadingPage.tsx
> +  }, [progress])
Я бы вынес это в кастомный хук useProgress

2022-11-01 21:48 UTC, khitrind commented on packages/client/src/pages/GameLoadingPage/GameLoadingPage.tsx
> +  }, [progress])
И наверное после этого унес внутрь ProgressBar - так как эта логика явно про него

2022-11-01 21:48 UTC, khitrind commented on packages/client/src/pages/GameLoadingPage/index.ts
> +export { default } from './GameLoadingPage';
Добавьте плз правило про только именованные экспорты https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-default-export.md

2022-11-01 21:48 UTC, khitrind commented on yarn.lock
> +yup@0.32.11:
Почему столько изменений в локе, если новых библиотек не добавлялось?

2022-11-04 10:17 UTC, DianaIvanovna commented on packages/client/src/components/ProgressBar/hooks/useProgress.tsx
> +};
мне кажется можно сократить: 

```
useEffect(() => {
    let id: ReturnType<typeof setInterval> = 0;

    if (running) {
      id = setInterval(() => {
        setProgress(prev => prev + 5);
      }, 500);
    }
    return () => {
      clearInterval(id);
    };
  }, [running]);

  useEffect(() => {
    if (progress === 100) {
      setRunning(false);
    }
  }, [progress]);
```

2022-11-04 10:19 UTC, DianaIvanovna commented on packages/client/src/hooks/useMountEffect.ts
>  export const useMountEffect = (effectCallback: () => (() => void) | void) => {
useMountEffect должен быть без параметров, думаю можно так написать :

```
export const useMountEffect = (effectCallback: () => (() => void) | void) => {
  useEffect(effectCallback);
};
```

2022-11-04 10:21 UTC, DianaIvanovna commented on packages/client/src/pages/LoginPage/LoginPage.tsx
Я вроде убирала отсюда useEffect , но видимо время ребейса невнимательно сделала. 
Уберу useEffect в своей ветке

2022-11-04 10:33 UTC, DianaIvanovna approved these changes

2022-11-04 12:55 UTC, khitrind approved these changes

2022-11-04 12:55 UTC, khitrind commented on packages/client/src/components/ProgressBar/hooks/useProgress.tsx
> +  return [progress];
```suggestion

return [progress === 100]
```

2022-11-04 13:34 UTC, merged