Pra 102 добавить 2 ои webapi
yandex-team-01/middle.game.praktikum.yandex pull request #40
Opened 2022-12-08 17:17 UTC by Victoriya0993

### Какую задачу решаем
Добавляем второй API. С командой решили, что это будет геолокация. 

По умолчанию в игре стоит английский язык. В случае если геолокация определяет, что пользователь  находится на территории России, появляется алерт с предложением сменить язык на русский. Если "Ок" - язык меняется,.

После смены языка нас перекидывает на стартовую страницу. Если есть предложения, как при смене языка остаться на той же странице, обязательно пишите

### Скриншоты/видяшка (если есть)

https://user-images.githubusercontent.com/90398540/206519386-b107068a-8eaa-49ae-bb18-07c1b0b722d1.mp4

### TBD (если есть)

2022-12-08 17:35 UTC, user14052020 approved these changes
Супер) только если ошибка я бы предложил выводить это как console.error() вместо console.log()

2022-12-09 05:33 UTC, FedoseevSM commented
Спасибо, классно! Есть нюансы:
- Почему API запрос не в экшене Redux?

- Лучше не использовать Snake Case, так как у нас везде Camel Case

- Лучше, наверное, делать сравнение языка не с массивом, а напрямую полученный язык с действующим языком и если у нас язык не совпадает, тогда сравнить с массивом всех наших языков и если у нас будет твой язык мы предложим сменить язык, а если не будет, тогда даже не предложим или предложим сменить на английский

2022-12-09 10:26 UTC, khitrind requested changes
Привет, идея супер, но с реализация я бы еще покрутил. Мне кажется, что стоит:

- превратить GeoController просто в функцию (помимо не особой надобности класса, с таким способом создания, на ssr будут проблемы, так как если мы создаем класс просто в модуле, то у нас получится один инстанс на всех пользователей);
- компонент Location - это не компонент, а просто  хук;
- давайте не будем агрессивно редиректить, а просто предложим сменить язык (попутно сохранив преференсы пока что в localStorage)

2022-12-09 10:26 UTC, khitrind commented on packages/client/src/api/GeoController.ts
> +export class GeoController {
Для чего здесь классс если в нем всего одна функция и как будто вообще никакая информация не хранится?

2022-12-09 10:26 UTC, khitrind commented on packages/client/src/api/GeoController.ts
> +export class GeoController {
```
export const reverseGeocoding = async <T>(options: RequestInit): Promise<T> => {
  const response = fetch(`${env.GEO_CODER}`, {
    ...options,
    mode: 'cors',
    headers: {
      'Content-Type': 'application/json',
      Accept: 'application/json',
      Authorization: 'Token ' + token,
    },
  }).then(res => {
    if (!res.ok) {
      return Promise.reject(res.status);
    }

    const contentType = res.headers.get('content-type');

    if (contentType && contentType.indexOf('application/json') !== -1) {
      return res.json();
    }
    if (contentType && contentType.indexOf('text/plain') !== -1) {
      return res.text();
    }

    return res;
  }) as Promise<T>;

  return response;
};

```

2022-12-09 10:26 UTC, khitrind commented on packages/client/src/api/GeoController.ts
> +    const response = fetch(`${env.GEO_CODER}`, {
И для чего тут generic, если эта функция всегда возвращает `ILocation`

2022-12-09 10:26 UTC, khitrind commented on packages/client/src/components/Location/Location.tsx
> +        navigator('/');
Ой, тут как будто может получится не очень приятно для пользователя, он заходит и мы его сразу редиректим( Давай просто выводить попапчик тип, хотите ли вы сменить язык?

2022-12-09 10:26 UTC, khitrind commented on packages/client/src/store/geolocation/GeoActions.ts
> +      const res: ILocation = await geoController.reverseGeocoding({
```suggestion
      const res = await reverseGeocoding({
```

2022-12-09 10:26 UTC, khitrind commented on packages/client/src/store/geolocation/GeoSelectors.ts
> +  geolocation => geolocation.location
```suggestion
  ({geolocation}: RootState) => geolocation.location
```

2022-12-09 12:15 UTC, Victoriya0993 commented on packages/client/src/components/Location/Location.tsx
> +        navigator('/');
при смене языка с помощью i18next нас перекидывает на 404. Решила принудительно отправлять его на стартовую при смене языка. Но сейчас поменяла редирект на текущую страницу (с которой он поменял язык)

2022-12-09 12:33 UTC, Victoriya0993 commented on packages/client/src/store/geolocation/GeoSelectors.ts
> +  geolocation => geolocation.location
Тут у меня ts прям ругается, если ему явно указать geolocation. Пока оставила как есть (по аналогии со всеми остальными селекторами)

2022-12-10 20:05 UTC, khitrind commented on packages/client/src/constants/Env.ts
> +  TOKEN_FOR_GEO_CODER: '3f663f65448628e0b9420a26933a0b03c3477c7f',
Не не так, он должен лежать в идеале у каждого в файлике env и приложения на старте его считывает и подставляет. Его даже комитить не надо в репо.

2022-12-10 20:06 UTC, khitrind approved these changes
Вынести токен в env и думаю можно комитить, все нормик!)

2022-12-10 20:06 UTC, khitrind commented on packages/client/src/utils/geoLocationAPI.ts
> +  };
Эта функция как будто вообще не используется

2022-12-11 09:12 UTC, merged