Pra 40 добавить oauth авторизацию
yandex-team-01/middle.game.praktikum.yandex pull request #42
Opened 2022-12-09 17:55 UTC by user14052020

### Какую задачу решаем
[Добавить OAuth авторизацию](https://linear.app/teamproject/issue/PRA-40/dobavit-oauth-avtorizaciyu)

Для реализации изменен порт клиента с 3000 на 5000, так как согласно скрытой от глаз документации api practicum "ручка" [get_oauth_yandex_service_id](https://ya-praktikum.tech/api/v2/swagger/#/Oauth/get_oauth_yandex_service_id)  принимает только 5000 порт для localhost. 

Однако этого оказалось недостаточно, чтобы авторизовать пользователя, так как ручка [post_oauth_yandex](https://ya-praktikum.tech/api/v2/swagger/#/Oauth/post_oauth_yandex) на текущий момент не принимает запросы от localhost. Продолжение следует после переезда в облако
### Скриншоты/видяшка (если есть)

### TBD (если есть)

https://user-images.githubusercontent.com/65355827/206762958-592fbdd9-e59d-4f03-a5f8-c49c67913776.mov

<img width="1263" alt="Screenshot 2022-12-09 at 22 53 08" src="https://user-images.githubusercontent.com/65355827/206763211-0abc5274-aa8e-46aa-ab7d-327b7f608db0.png">
<img width="732" alt="Screenshot 2022-12-09 at 22 54 39" src="https://user-images.githubusercontent.com/65355827/206763463-dfa95530-fc12-4f79-bf21-21bde0fbbbe6.png">

2022-12-09 20:40 UTC, khitrind requested changes

2022-12-09 20:40 UTC, khitrind commented on packages/client/src/components/Routing/Routing.tsx
> +        <Route path="/"        element={
Тут как будто форматирование разнесло

2022-12-09 20:40 UTC, khitrind commented on packages/client/src/pages/Landing/Landing.tsx
> +    }
Давай не будет прям так внутри компонента это описывать. Такое сложно тестить + грязновато выглядит. D В данном случае тут должно быть функция запроса к api это соответственно `fetchOAuthStepOneGetServiceIdFromApiPracticum` а логику с проверкой кода давай вынесем в отдельный хук условный useOAuth. В нем соответственно и будем то что сейчас в mount эффекте

2022-12-09 20:40 UTC, khitrind commented on packages/client/src/store/auth/AuthActions.ts
> +    console.log(res);
console.log из продакшена принято удалять

2022-12-09 20:40 UTC, khitrind commented on packages/client/src/store/auth/AuthActions.ts
> +    console.error(error);
Для ошибок у нас вроде компонентик есть в который это задиспатчить можно

2022-12-09 20:40 UTC, khitrind commented on packages/client/src/store/auth/AuthActions.ts
> +      return thunkApi.rejectWithValue('Ошибка выхода');
А поч тут не i18n?

2022-12-10 11:00 UTC, user14052020 commented
> Привет, может перенесем кнопку OAuth в LoginForm?
> 
> ![image](https://user-images.githubusercontent.com/60156828/206845258-a4583edb-4572-435e-93ad-8340580a6337.png)

Привет. Если расположить кнопку Яндекса на форме Авторизации, тогда пользователь узнает о том, что можно начать игру без ввода авторизационных/регистрационных данных, только после перехода на страницу Авторизации. С другой стороны эту кнопку можно расположить и на форме Регистрации, но в обоих этих случаях будет выглядеть так, как будто пользователю нужно ввести данные от Яндекса или же пользователь обнаружит кнопку Яндекс только после того как введет все данные, так как статистически чаще всего на формах авторизации/регистрации не бывает других кнопок.

2022-12-10 20:16 UTC, khitrind requested changes
Выглядит уже почти отлично, давай разберемся с фкнцией перевода (я в личке все описал) и логику с экстрактом кода вынесем как в сниппете (ну и ветку поребейзить)

2022-12-10 20:16 UTC, khitrind commented on packages/client/src/hooks/useFullScreen.ts
> +      typeof document !== 'undefined' &&
`const isSsr = getEnvSsr();`

2022-12-10 20:16 UTC, khitrind commented on packages/client/src/hooks/useOAuth.ts
> +export const useOAuth = (queryString: string) => {
Это не хук - просто функция доставания кода из url - `extractOAuthCode`

2022-12-10 20:16 UTC, khitrind commented on packages/client/src/hooks/useOAuth.ts
> +export const useOAuth = (queryString: string) => {
А сам хук - чет в этом роде и его можно просто в апп положить по идее.


```
export const useCheckOauthCode = () => {
  //третий шаг oAuth - отправляем код полученный после редиректа на страницу согласия на авторизацию
  useMountEffectOneCall(() => {
    const queryString = window.location.search;
    const urlParams = new URLSearchParams(queryString);
    const code = urlParams.get('code');
    if (code) {
      fetchOAuthStepThreeGetApprove(code);
    }
  });
};

```

2022-12-12 06:54 UTC, khitrind approved these changes
посмотри последние комменты плз и давай комитить задачу, а то уже сумасшествие какое-то происходит

2022-12-12 06:54 UTC, khitrind commented on packages/client/src/App.tsx
> +  const dispatch = useAppDispatch();
useBoundAction

2022-12-12 06:54 UTC, khitrind commented on packages/client/src/constants/Env.ts
>  };
такая функция уже есть в проекте, а еще на на 10 строчке странная вещь - typeof всегда возвращает строку, получается она никогда не будет undefiend, только 'undefined'

2022-12-12 11:40 UTC, DianaIvanovna approved these changes

2022-12-12 14:35 UTC, merged