Pra 110: подключить helmet и настроить seo
yandex-team-01/middle.game.praktikum.yandex pull request #43
Opened 2022-12-10 12:40 UTC by FedoseevSM

Так как сейчас проблемы с авторизацией пользователя (дефолтным стором) на SSR, временно отключена проверка авторизации для страницы Leaderboard

**Выполнено:**
1. Добавлен компонент SEO
2. Настроен react-helmet-async для SSR

**Ошибки:**
1. i18next не определяется при рендеринге SSR, необходимо подключить мидлвар (работает в SPA)
2. Слетела вёртска Leaderboard, так как изначально выравнивание сделано не правильно

2022-12-10 20:03 UTC, khitrind requested changes
Привет, выглядит отл, но нужно сделать еще пару вещей:

- 100% надо поребейзить ветку, так как там очень многое поменялось;
- давай не будем просто так руками реплейсить тайтл - в доке примеры как сделать чуть более generic решение;

2022-12-10 20:03 UTC, khitrind commented on packages/client/src/hooks/useFullScreen.ts
> +      !document.fullscreenElement
Тут много чего поменялось поребейзи ветку пожлуйста

2022-12-10 20:29 UTC, FedoseevSM commented on packages/server/utils/renderHtml.ts
> +  );
@khitrind Это не работает для SSR

2022-12-11 16:18 UTC, DianaIvanovna approved these changes

2022-12-14 20:36 UTC, FedoseevSM commented
Задача перенесена на следующий спринт

2022-12-14 20:36 UTC, closed without merging