feat: pra-117 игра - добавить вывод на экран текущей скорости пользователя и npc
yandex-team-01/middle.game.praktikum.yandex pull request #49
Opened 2022-12-17 10:47 UTC by FedoseevSM

Добавлен вывод скорости игрока и скорости враждебных npc

Реализация:
Создан класс ShowSpeed, который рендерит счётчики в canvas

![speed on screen](https://i.imgur.com/EDI3Ji7.png)

2022-12-17 12:40 UTC, user14052020 requested changes
Спасибо! Получилось солидно) Есть два крошечных предложения:
1) Возможно стоит переименовать отображение скорости на экране игры, так как сейчас для новичка непонятно будет что такое player:7.00.
2) На старте скорость Киси и Хаги одинаковая, но далее скорость их меняется в зависимости от того кто из них сколько поймал докторов, соответсвенно нужно два поля для обозначения скорости npc. 

Таким образом, возможно, эти три строчки(скорость игрока, скорость хаги,скорость киси) удачно было бы разместить под счетчиком монеток и сделать шрифт этой информации вдвое меньше

2022-12-17 16:44 UTC, FedoseevSM commented
![speed on screen](https://i.imgur.com/T2h5Rqm.png)

2022-12-17 17:44 UTC, FedoseevSM commented
![speed on screen](https://i.imgur.com/mF0NDK5.png)

2022-12-17 19:03 UTC, FedoseevSM commented
![speed sprite on screen](https://i.imgur.com/jx9kK7d.png)

2022-12-17 19:10 UTC, user14052020 commented on packages/client/src/logic/ShowSpeed.ts
> +      68,
Традиционные магические числа) сделай пожалуйста ребейз, и добавь эти цифры в константу game_settings

2022-12-17 19:11 UTC, user14052020 commented on packages/client/src/logic/ShowSpeed.ts
> +      72,
Тоже самое про магические числа

2022-12-17 19:12 UTC, user14052020 commented on packages/client/src/logic/ShowSpeed.ts
> +      72,
И тут магические числа красиво будет перенести к остальным размерам в константе game_settings

2022-12-17 19:18 UTC, user14052020 requested changes
Почти идеально, но чтобы не плодить работу для того, кто будет работать над правками после 8 спринта, давай приведем нейминг к общему виду)

2022-12-17 19:18 UTC, user14052020 commented on packages/client/src/logic/ShowSpeed.ts
> +export class ShowSpeed {
Не хотелось бы придираться к мелочам) но showSpeed удачное имя для функции а не для класса, чтобы сохранить однообразие может стоит использовать существительное в названии класса как в Timer например Speedometer

2022-12-18 03:40 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    const defineX = 72;
Перенеси пожалуйста эти значения тоже в константу с настройками игры

2022-12-18 03:42 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    const kissy = this.npcControll.arrNpc[0].speed.toFixed(2);
Не самое удачное решение поиска кисси, так как если кто изменит массив, но он вряд ли вспомнит что тут есть такая зависимость, поэтому правильно будет отфильтровать массив по типу enemy_kissy

2022-12-18 03:43 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    const huggy = this.npcControll.arrNpc[1].speed.toFixed(2);
Не самое удачное решение поиска хагги , так как если кто изменит массив, но он вряд ли вспомнит что тут есть такая зависимость, поэтому правильно будет отфильтровать массив по типу enemy_huggy

2022-12-18 03:45 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    const defineY = 48;
Перенеси пожалуйста эти значения тоже в константу с настройками игры game_settings с понятным названием например playerSpidometerX и playerSpidometerY

2022-12-18 03:50 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +  speedHuggy() {
При нейминге сперва указывается основной элемент а затем зависимый от него, например здесь корректно huggySpeedometer ранее Дмитрий на это  указывал [здесь](https://github.com/yandex-team-01/middle.game.praktikum.yandex/pull/46#discussion_r1047121786)

2022-12-18 03:51 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    this.speedKissy();
При нейминге сперва указывается основной элемент а затем зависимый от него, например здесь корректно huggySpeedometer и т д, ранее Дмитрий на это указывал https://github.com/yandex-team-01/middle.game.praktikum.yandex/pull/46#discussion_r1047121786

2022-12-18 03:56 UTC, user14052020 requested changes
если честно повторно изучив код, мне хочется тебе предложить переделать class Speedometer в class SpeedometerController и создать новый класс Speedometer, который будет принимать уникальные для конкретного спидометра данные и обрисовывать их. То есть сделать по аналогии с классами NPCController  и NPC, так как сейчас три одинаковые функции  speedPlayer() speedHuggy() и speedKissy() являются дублированием кода, а в первом модуле нас учили избегать такого

2022-12-18 04:32 UTC, user14052020 requested changes
1. Пожалуйста вынеси значения координат для каждого спидометра в константу game_settings, 
2. переименуй функции рендера каждого спидометра в соответствии с принятой в проекте логикой нейминга 
3. и напиши пожалуйста более универсальную логику поиска хаги-кисси в массиве, 
4. в комментариях и в личку описал подробнее)

2022-12-18 04:32 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    const defineY = 68;
Перенеси пожалуйста эти значения тоже в константу с настройками игры game_settings с понятным названием например huggySpeedometerX и huggySpeedometerY

2022-12-18 04:32 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    const defineY = 88;
Перенеси пожалуйста эти значения тоже в константу с настройками игры game_settings с понятным названием например kissySpeedometerX и kissySpeedometerY

2022-12-18 04:32 UTC, user14052020 commented on packages/client/src/logic/const.ts
> +  SPEEDOMETER = 'speed'
```suggestion
  SPEEDOMETER = 'speedometer'
```
это ведь не только скорость но и картинка спидометра

2022-12-18 04:32 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    this.speedKissy();
мы ведь не только скорость получаем в итоге а рендерим спидометр, соотвественно вместо спид следовало бы употребить спидометр. При нейминге сперва указывается основной элемент а затем зависимый от него, например здесь корректно huggySpeedometer и т д, . ранее Дмитрий на это указывал [ранее Дмитрий на это указывал](https://github.com/yandex-team-01/middle.game.praktikum.yandex/pull/46#discussion_r1047121786)

2022-12-18 04:32 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    const huggy = this.npcControll.arrNpc[1].speed.toFixed(2);
Не самое удачное решение поиска huggy, так как если кто изменит массив, но он вряд ли вспомнит что тут есть такая зависимость, поэтому правильно будет отфильтровать массив по типу enemy_huggy

2022-12-18 04:32 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    const kissy = this.npcControll.arrNpc[0].speed.toFixed(2);
Не самое удачное решение поиска kissy, так как если кто изменит массив, но он вряд ли вспомнит что тут есть такая зависимость, поэтому правильно будет отфильтровать массив по типу enemy_kissy

2022-12-18 04:32 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    const defineY = 48;
Перенеси пожалуйста эти значения тоже в константу с настройками игры game_settings с понятным названием например playerSpeedometerX и playerSpeedometerY

2022-12-18 04:32 UTC, user14052020 commented on packages/client/src/logic/const.ts
> +import speed from '/src/assets/images/game-ico-speed.png';
```suggestion
import speedometer from '/src/assets/images/game-icon-speedometer.png';
```
используй пожалуйста полные наименования чтобы в будущем не возникало сомнений о чем речь, так как фактически это не иконка скорости, а иконка спидометра)

2022-12-18 04:43 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    const player = this.playerOne.speed.toFixed(2);
```suggestion
    const playerSpeedometerText = this.playerOne.speed.toFixed(2);
```

2022-12-18 04:43 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    const huggy = this.npcControll.arrNpc[1].speed.toFixed(2);
```suggestion
    const huggySpeedometerText = this.npcControll.arrNpc[1].speed.toFixed(2);
```

2022-12-18 04:44 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    const kissy = this.npcControll.arrNpc[0].speed.toFixed(2);
```suggestion
    const kissySpeedometerText = this.npcControll.arrNpc[0].speed.toFixed(2);
```

2022-12-18 05:54 UTC, FedoseevSM commented on packages/client/src/logic/Speedometer.ts
> +    const defineY = 68;
@user14052020 логика поиска в массиве очень проста, она соответствует id персонажа в массиве
пока что, на мой взгляд, проще некуда
если знаешь проще, без циклов итерации и типизации - напиши, пожалуйста
![ids in array](https://i.imgur.com/onKGQ4I.png)

2022-12-18 05:58 UTC, FedoseevSM commented on packages/client/src/logic/Speedometer.ts
> +    const huggy = this.npcControll.arrNpc[1].speed.toFixed(2);
Ок

2022-12-19 15:16 UTC, user14052020 requested changes
playerSpeedometer();
     huggySpeedometer();
     kissySpeedometer();

данные функции нужно объединить в одну, так как они одинаковые

2022-12-20 05:37 UTC, FedoseevSM commented
> слушай я совсем забыл что у нас hp и money отрисовывается прямо в классе Player, на скрине. Поэтому чтобы сохранить единообразие, пожалуйста удали классы speedometer и speedometer контролер и добавь в класс Player и в классы EnemyHuggy и EnemyKissy функцию renderSpeedometer, которая будет рисовать spedometer по аналогии с функцией renderHPandScore и вызывай ее в функции render в этих классах. К тому же это позволит значительно сократить количество кода)
> 
> <img alt="Screenshot 2022-12-20 at 08 01 30" width="775" src="https://user-images.githubusercontent.com/65355827/208572318-df42b0a6-2193-4387-9c60-cbbb06adbbeb.png">

Вроде бы, сократить количество кода это не главная задача. Мне не понравилось то, что хп и деньги написаны в плейере. Кажется их лучше вынести в отдельный класс, по типу отдельного компонента, тогда будет единообразие. Но это в другой задаче

2022-12-20 06:18 UTC, FedoseevSM commented
> > слушай я совсем забыл что у нас hp и money отрисовывается прямо в классе Player, на скрине. Поэтому чтобы сохранить единообразие, пожалуйста удали классы speedometer и speedometer контролер и добавь в класс Player и в классы EnemyHuggy и EnemyKissy функцию renderSpeedometer, которая будет рисовать spedometer по аналогии с функцией renderHPandScore и вызывай ее в функции render в этих классах. К тому же это позволит значительно сократить количество кода)
> > <img alt="Screenshot 2022-12-20 at 08 01 30" width="775" src="https://user-images.githubusercontent.com/65355827/208572318-df42b0a6-2193-4387-9c60-cbbb06adbbeb.png">
> 
> Вроде бы, сократить количество кода это не главная задача. Мне не понравилось то, что хп и деньги написаны в плейере. Кажется их лучше вынести в отдельный класс, по типу отдельного компонента, тогда будет единообразие. Но это в другой задаче

Весь UI потом, как дальнейшее развитие, если будет время, хорошо бы вместе объединить, но в то же время отдельные элементы интерфейса изолировать в компонент

Мне не нравится, когда в одном файле 1000 строк из разных компонентов

Тем более, мы уже пришли к атомарности во всем проекте

2022-12-20 10:45 UTC, DianaIvanovna approved these changes

2022-12-21 03:25 UTC, user14052020 requested changes
- [я не против атомароности) но тогда нужно доработать текущий код.](https://github.com/yandex-team-01/middle.game.praktikum.yandex/pull/49#pullrequestreview-1221939030)
- [ посмотри пожалуйста, эти три функции (huggySpeedometer, kissySpeedometer, playerSpeedometer) делают одно и тоже)](https://github.com/yandex-team-01/middle.game.praktikum.yandex/pull/49#discussion_r1051525829)
- [соотвественно их нужно объединить в одну функцию) то есть удалить парочку из них и оставить только одну)](https://github.com/yandex-team-01/middle.game.praktikum.yandex/pull/49#pullrequestreview-1223079095)

2022-12-21 03:25 UTC, user14052020 commented on packages/client/src/logic/Speedometer.ts
> +    this.kissySpeedometer();
я не против атомароности) но тогда нужно доработать текущий код. смотри, эти три функции (huggySpeedometer, kissySpeedometer, playerSpeedometer) делают одно и тоже, соотвественно 

1. удали пожалуйста функции  huggySpeedometer и kissySpeedometer;  
2.  оставь только playerSpeedometer и переименуй ее в prepareSpeedometer  
3. передавай в prepareSpeedometer координаты и текст в качестве параметров 
То есть сделать по аналогии с классами NPCController и NPC  или Collisions и ClashesController

2022-12-21 08:34 UTC, FedoseevSM commented on packages/client/src/logic/Speedometer.ts
> +    this.kissySpeedometer();
Передаю данные в качестве параметров в контроллер
spriteX, spriteY, speedometerValue, speedometerText, textX, textY

Сейчас Speedometer это вьюшка для отрисовки, а SpeedometerController как раз подобие описанное тобой prepareSpeedometer

Во вьюшке можно отключить нужный спидометр, не удаляю его, а также переименовать, если нужно
Все спидометры в одном месте, это удобно. Не нужно ходить для настроек в каждого юзера отдельно

Потом, когда-нибудь, в будущем при расширении, как вариант, можно отключить рендер во вьюшке спидометра и импортировать prepareSpeedometer(), содержащий в себе    
```
    this.playerSpeedometer();
    this.huggySpeedometer();
    this.kissySpeedometer();
```
в главную вьюшку ui с панелью характеристик игры

Вроде бы, вполне читаемо
```
  private playerSpeedometer() {
    const spriteX = GAME_SETTINGS.SPEEDOMETER_SPRITE_PLAYER_X;
    const spriteY = GAME_SETTINGS.SPEEDOMETER_SPRITE_PLAYER_Y;
    const speedometerValue = this.playerOne.speed;
    const speedometerText = `Player`;
    const textX = GAME_SETTINGS.SPEEDOMETER_TEXT_PLAYER_X;
    const textY = GAME_SETTINGS.SPEEDOMETER_TEXT_PLAYER_Y;
    this.speedometerController.render({
      spriteX,
      spriteY,
      speedometerValue,
      speedometerText,
      textX,
      textY,
    });
  }
```

2022-12-22 05:45 UTC, user14052020 requested changes
Логика очень простая: после каждого мерджа у нас не должно нарушаться единообразие кода, это значит что раз классы NPCController и NPC или Collisions и ClashesController были написаны раньше чем SpeedometerController и Speedometer, то нужно привести логику SpeedometerController и Speedometer к виду  NPCController и NPC или Collisions и ClashesController, поэтому: 

1. удали пожалуйста функции huggySpeedometer и kissySpeedometer;
2. оставь только playerSpeedometer и переименуй ее в prepareSpeedometer
3. передавай в prepareSpeedometer координаты и текст в качестве параметров

То, что ты предлагаешь, очень здорово и я горячо поддерживаю такие изменения, но только если они будут выполнены в рамках отдельного PR, в результате которого будут внесены изменения в весь проект, чтобы сохранить единообразие

2022-12-22 22:18 UTC, FedoseevSM commented
> Логика очень простая: после каждого мерджа у нас не должно нарушаться единообразие кода, это значит что раз классы NPCController и NPC или Collisions и ClashesController были написаны раньше чем SpeedometerController и Speedometer, то нужно привести логику SpeedometerController и Speedometer к виду NPCController и NPC или Collisions и ClashesController, поэтому:
> 
> 1. удали пожалуйста функции huggySpeedometer и kissySpeedometer;
> 2. оставь только playerSpeedometer и переименуй ее в prepareSpeedometer
> 3. передавай в prepareSpeedometer координаты и текст в качестве параметров
> 
> То, что ты предлагаешь, очень здорово и я горячо поддерживаю такие изменения, но только если они будут выполнены в рамках отдельного PR, в результате которого будут внесены изменения в весь проект, чтобы сохранить единообразие

Ок, переместил в один метод
Каждый спидометр обозначен функцией, чтобы изолировать переменные для создания типов ts

2022-12-23 02:59 UTC, user14052020 requested changes
нам нужно получить логику так, как это сделано в классах NpcController и Npc или ClashesController и Collisions

1. в классе speedometer удали пожалуйста playerSpeedometer, huggySpeedometer, kissiSpeedometer
2. создай пожалуйста в константах массив, в котором будет три элемента: playerSpeedometerOptions и его параметры, huggySpeedometerOptions и его параметры, kissiSpeedometerOptions и его параметры
3. в классе speedometController создай пожалуйста функцию, которая будет в цикле пробегать по массиву с опциями для спидометров и создавать новый экземпляр класса speedometer для каждого элемента массива.

2022-12-26 04:22 UTC, FedoseevSM commented
@user14052020 Внеси, пожалуйста, самостоятельно те правки, которые считаешь нужным до полной реализации, если такие есть, в этот пр

2022-12-26 04:48 UTC, user14052020 approved these changes
Образцовая работа.

2022-12-26 07:46 UTC, merged