feat: pra-122 игра - увеличивать скорость врагов и пользователя при наборе определенного количества очков
yandex-team-01/middle.game.praktikum.yandex pull request #51
Opened 2022-12-18 13:02 UTC by FedoseevSM

При достижении определенного количества монет, меняются уровни, на которых увеличивается скорость персонажей, что создает интерес собрать больше монет и придает сложности в игре

**Реализация:**
Создан класс Levels, который отвечает за смену уровней
Массив с уровнями хранится в файле const

Некоторый код закомментирован для теста и предложений по улучшению, он будет удалён перед мерджем

2022-12-19 15:14 UTC, user14052020 requested changes
1) не уверен, что текущая реализация отвечает изначальной задумке, в комменте указал подробнее

 2) есть вопрос к оформлению -- сейчас вся эта информация про скорость занимает много места, во вложении пример как предлагаю.

![68747470733a2f2f692e696d6775722e636f6d2f6a78396b4b37642e706e67](https://user-images.githubusercontent.com/65355827/208456813-6148139b-c971-4b07-a04e-12e661f6d6f5.png)

2022-12-19 15:14 UTC, user14052020 commented on packages/client/src/logic/Levels.ts
> +          this.playerOne.speed + GAME_SETTINGS.PLAYER_COLLISION_SPEED_BONUS;
предполагалось, что у каждого lvl свой показатель скорости для enemy и player, соотвественно код должен выглядеть так
if (score === level.score) {
         this.playerOne.speed =
          level.speed;

 this.npcControll.arrNpc.forEach(npc => {
           npc.speed = npc.speed +  level.speed;
         });
}

то что получилось сейчас нельзя назвать решением так как получается что мы оставили все как есть и просто выводим лвл на экран)

2022-12-20 03:11 UTC, user14052020 commented on packages/client/src/logic/Levels.ts
> +          this.playerOne.speed + GAME_SETTINGS.PLAYER_COLLISION_SPEED_BONUS;
например набрал 10 очков, перешел на 2 второй уровень, где скорость пользователя 8, а у врагов 9 и т д

2022-12-20 03:20 UTC, user14052020 commented on packages/client/src/logic/ClashesController.ts
> +          this.playerOne.speed - GAME_SETTINGS.NPC_ENEMY_COLLISION_SPEED_DAMAGE;
это лишнее убери это пожалуйста

2022-12-20 03:22 UTC, user14052020 commented on packages/client/src/logic/Levels.ts
> +  levelInfo() {
переименуй пожалуйста в updateLevel

2022-12-20 22:36 UTC, FedoseevSM commented on packages/client/src/logic/Levels.ts
> +          this.playerOne.speed + GAME_SETTINGS.PLAYER_COLLISION_SPEED_BONUS;
> например набрал 10 очков, перешел на 2 второй уровень, где скорость пользователя 8, а у врагов 9 и т д

Стало гораздо лучше, спасибо!

2022-12-20 23:01 UTC, FedoseevSM commented on packages/client/src/logic/Levels.ts
> +  levelInfo() {
Вынес ее в конструктор. На мой взгляд, чем чище рендер, тем лучше. Подобные композиции, наверное, лучше изолировать для рендера

2022-12-21 03:32 UTC, user14052020 requested changes
какая то не очень читаемая конструкция получилась с levelInfo в конструкторе, в других сущностях мы так не делаем, поэтому лучше придерживаться единообразия, чтобы можно было легко ориентироваться в коде.

верни пожалуйста как было и просто переименуй levelInfo в prepareLevelInfo, функции принято называть используя глаголы поясняющие что происходит в функции)

2022-12-21 06:15 UTC, FedoseevSM commented
> какая то не очень читаемая конструкция получилась с levelInfo в конструкторе, в других сущностях мы так не делаем, поэтому лучше придерживаться единообразия, чтобы можно было легко ориентироваться в коде.
> 
> верни пожалуйста как было и просто переименуй levelInfo в prepareLevelInfo, функции принято называть используя глаголы поясняющие что происходит в функции)

Обновил имя переменной

Метод сделан в конструкторе для того, чтобы указать приватность метода и скрыть для доступа извне. Так как в рендере (прототипном, публичном методе), предположительно, может существовать несколько методов, внутри класса, вероятно, лучше к ним обращаться через подобное объявление. Мы не сможем обратиться к приватным методам извне, впринципе это не нужно, но, иногда, очень редко, можно делать трюки, чтобы обратиться.

Какой стратегии или шаблона написания придерживаешься? Кажется то, что подход с приватными методами удобен и облегчит нам написание кода.

В дальнейшем, если мы будем расширяться, когда-нибудь потом, из класса Levels, в теории, может быть удален рендер впринципе и также этот приватный метод. Так, как Levels не является главным View компонентом для инициализации интерфейса.

2022-12-22 13:59 UTC, user14052020 approved these changes
love it

2022-12-22 19:29 UTC, DianaIvanovna approved these changes

2022-12-24 10:09 UTC, merged