feat: проверка auth на сервере
yandex-team-01/middle.game.praktikum.yandex pull request #52
Opened 2022-12-18 14:19 UTC by DianaIvanovna

### Какую задачу решаем
[PRA-115 Проверка авторизации на сервере мидлевар](https://linear.app/teamproject/issue/PRA-115/proverka-avtorizacii-na-servere-midlevar) 

С помощью мидлевар cookieParser забираю куки. 
Мидлевар auth отправляет запрос проверки авторизации auth/user с куки. Если человек авторизован, то добавляю объект пользователя в редакс. 

Нюансы: 
**- не будет работать, пока не перейдем на поддомен яндекса.** 

Чтобы проверить что функционал работает, можно руками скопировать куки 
красное - куки с поддомена яндекса
зеленое - сама добавила куки руками и он их видит на нашем сервере
![image](https://user-images.githubusercontent.com/60156828/208303204-ff36d0c5-ef5e-4b7f-9a36-f5f459f1651d.png)

**- Добавила https сертификат и теперь сервер доступен по адресу https://localhost:3001/**
сначала покажет ошибку, нужно нажать дополнительно и перейти на localhost принудительно 
![image](https://user-images.githubusercontent.com/60156828/208303368-c8fd0280-6e6b-4480-807f-f7c427c15248.png)

2022-12-19 12:01 UTC, khitrind requested changes
Сертификаты в репо не храним, остальное вроде норм)

2022-12-19 12:01 UTC, khitrind commented on cert.pem
> +-----BEGIN CERTIFICATE-----
Тэкс, мы вообще не храним никакие криды и сертефикаты в репо. Каждый должен либо сгенерить себе свой, либо пошарьте между друг другом. Но на будущее, ни пароли ни сертификаты ни логины мы не храним в репо - никогда.

2022-12-19 16:26 UTC, user14052020 approved these changes
🦾

2022-12-19 16:26 UTC, user14052020 commented on packages/server/package.json
> +    "axios": "^1.2.1",
```suggestion
    "axios": "1.2.1",
```

2022-12-21 09:06 UTC, Victoriya0993 approved these changes

2022-12-21 09:13 UTC, khitrind approved these changes

2022-12-21 09:14 UTC, merged