Pra 113 продумать и сделать api форума
yandex-team-01/middle.game.praktikum.yandex pull request #53
Opened 2022-12-18 18:29 UTC by Victoriya0993

### Какую задачу решаем
Продумать и реализовать api форума на бэке.

На данный момент добавлены две сущности:
- топик
- комментарий к топику

В приложении появились слои (каждому слою соответствует своя папка): 
- контроллеры
- сервисы
- модели
Буду рада, если у вас есть идеи как  лучше разбить/сгруппировать папки.

В docker-compose добавила образ pgAdmin, мне показалось, так проще подключаться и смотреть базу, чтобы не устанавливать отдельно pgAdmin.

Для тестирования работы api можно использовать Postman.

* В текущей сборке докера нужно каждый раз очищать контейнеры и образы, чтобы собрать заново с изменениями.
* У меня вопрос, как не допустить пересечения по роутам с ssr? 

### Скриншоты/видяшка (если есть)

![image](https://user-images.githubusercontent.com/90398540/208313162-2aad7df4-b9c6-46fe-bddb-e6efdc3bc303.png)

![image](https://user-images.githubusercontent.com/90398540/208313197-f1579bb6-c42e-4f7c-bda7-a12d6730df0c.png)

![image](https://user-images.githubusercontent.com/90398540/208313267-540ccb4c-02c7-4448-808a-e3d6baa33ff3.png)

![image](https://user-images.githubusercontent.com/90398540/208313289-056453e6-0617-4f97-bd47-c50bda88407e.png)

### TBD (если есть)

2022-12-19 12:45 UTC, khitrind requested changes
Привет, в целом все выглядит очень не плохо, не есть некоторая мешанина абстракций все в одном месте. Как мне кажется стоит разделить логику примерно так:

- уровень роутинга;
- уровень сервисов;
- уровень работы с бд;

На уровне роутинга мы создаем роутер и мапим api роуты в сервисы что-то таком роде:

Мы определяем тут дефайним базовый url для сервиса и дальше мапим сабурлы к функциям сервиса.

```
export const forumRouter = (apiRouter: Router) => {
  const router: Router = Router();
  const service = forumService();

  router.get("/topic", service.getTopics);
 
 //  ...etc
   apiRouter.use("/feedback", router);
};
```



Соответственно внутри  сервиса мы определяем логику поведения, то есть обращаемся к [репозиторию](https://habr.com/ru/post/52173/) за данными и в зависимости от того что получили или не получили, возвращаем данные и статус.

```

const forumService = () => {
  const getTopics = (_req: Request, res: Response) => {
    forumRepos
      .getAll()
      .then(topics => res.status(200).json(topics))
      .catch(err => res.status(500).json({ error: ["db error", err] }));
      
      //...etc
  };

```

Ну и в самом репозитории определяются моедльки и способ работы с ними.

-------------------


В самом верху это соответственно выглядит как промапить сервисы на основной роутер и заиспользовать:

```
// inde.router.ts
const apiRouter: Router = Router();

forumRouter(apiRouter);
themeRouter(apiRouter);
...etc

```
Ну и в самом верху:

`app.use("/api", apiRouter);`


Как-то так, получится гораздо более структурировано и понятно)

2022-12-19 12:45 UTC, khitrind commented on packages/server/controllers/commentController.ts
> +    app.get('/comment', async function (req, res) {
```suggestion
    app.get('/comment', async function (_, res) {
```

2022-12-19 12:45 UTC, khitrind commented on packages/server/controllers/commentController.ts
> +    app.post('/comment', async function (req, res) {
Почитай что такое:

`import { Router } from "express";`

2022-12-19 12:45 UTC, khitrind commented on packages/server/index.ts
> +  apiController(app);
Мы разрешаем доступ к api не авторизованным польщователям? Нужно начать использовать auth middleware

2022-12-19 12:46 UTC, khitrind commented on packages/server/models/modelTopic.ts
> +}
Тип нужно доставить из модельки а не писать руками, можн опрям в интернете поискать get TS type from sequelize model

2022-12-19 16:40 UTC, helgamir reviewed
Круто, что добавила pgadmin! По api не могу ничего добавить, выглядит хорошо. Написала минимальные комментарии, это больше вопросы, чем предложения.
Спасибо!

2022-12-19 16:40 UTC, helgamir commented on packages/server/package.json
> +    "sequelize-typescript": "^2.1.5",
а мы не фиксируем версию разве?

2022-12-19 16:40 UTC, helgamir commented on packages/server/db.ts
> +// import { getTopicById } from './services/topicService';
тут должно быть закоменчено?

2022-12-23 08:00 UTC, khitrind approved these changes

2022-12-23 08:00 UTC, khitrind commented on packages/server/package.json
> +}
EOF

2022-12-23 10:49 UTC, helgamir approved these changes

2022-12-23 11:03 UTC, merged