feat: pra 106 подружить ssr с i18next
yandex-team-01/middle.game.praktikum.yandex pull request #54
Opened 2022-12-19 12:05 UTC by FedoseevSM

Управление i18next через серверную часть

**Сделано:**
- Роутинг внутри функции i18next
- Задействованы серверные мидлвари, отличающиеся от клиентских (автоопределение языка и конфигурация)
- Отдельный файл с настройками i18next для сервера

**Как работает:**
Создаются глобальные элементы window.initialLanguage, который содержит текущий язык и window.initialI18nStore, который содержит нужный словарь для html страницы в данный момент. Далее через скрипт, также как в SPA подменяются переменные и рендерится текст html. Каждое обновление страницы происходит новый рендер

**Временно отключено для теста:**
- База данных
- ReactStrickMode
- ReactSuspense
- ReactDOM.CreateRoot

2022-12-19 12:47 UTC, khitrind requested changes
Давай сегодня на встречке это пообсуждаем?)

2022-12-22 08:06 UTC, DianaIvanovna approved these changes

2022-12-22 15:29 UTC, FedoseevSM commented
1. i18n на сервере (проходит весь круг через клиент до рендера в html) с отдельными настройками для SSR
2. Обновленный файл .gitignore в корне проекта
3. Исключение в eslint для сгенерированного контента (exclude public)
4. Исключения в tsconfig для nodemodules (nolibcheck)
5. Ключи сертификата перенесены в папку /packages/server/keys для удобства активации docker
6. Устранена ошибка warn в prettier format (убран критерий width:50)

2022-12-22 17:01 UTC, khitrind commented on packages/client/src/main.tsx
> +  return dom;
Если ты возвращаешь dom из функции, то надо его там и определять

2022-12-22 17:01 UTC, khitrind commented on packages/server/index.ts
> +          .use(i18nextMiddleware.handle(i18n))
Почему тут ts-ignore?

2022-12-22 17:01 UTC, khitrind commented on packages/server/utils/renderHtml.ts
> +        req.i18n.services.resourceStore.data[language][namespace];
Почему тут ignore?

2022-12-22 19:14 UTC, FedoseevSM commented on packages/client/src/entry-server.tsx
> -      <React.Suspense>
Блин.. Спасибо!
Случайно затер при мердже. Не правильно сегодня смерджил в другой IDE, там оставались старые файлы и они каким-то образом переписались... Постараюсь больше так не делать

2022-12-22 20:25 UTC, FedoseevSM commented on packages/server/index.ts
> +          .use(i18nextMiddleware.handle(i18n))
Не нашел другого способа пофиксить...

2022-12-24 10:08 UTC, khitrind approved these changes

2022-12-24 15:43 UTC, merged