pra-46-Добавьте возможность переключать темы (Фронт)
yandex-team-01/middle.game.praktikum.yandex pull request #55
Opened 2022-12-21 11:05 UTC by user14052020

### Какую задачу решаем
[Добавьте возможность переключать темы (Фронт)](https://linear.app/teamproject/issue/PRA-46/dobavte-vozmozhnost-pereklyuchat-temy-front)
Для решения задачи на фронте был добавлен контекст в который передается текущая тема. Далее данный контекст принимается в компоненте ThemeTogglerButton и при нажатии меняет текущую тему. Данные записываются в localStore. 
### Скриншоты/видяшка (если есть)

https://user-images.githubusercontent.com/65355827/208889860-8cb68ea8-39bb-4892-a77c-0a0ac4f49634.mov

2022-12-21 11:16 UTC, user14052020 commented on packages/client/src/components/ThemeTogglerButton/ThemeContext.ts
> +    background: 'rgb(0, 0, 0)',
пробовал получать переменные из файла со стилями с помощью такой конструкции 
import styles from 'src/styles/variables.scss';
export const themes = {
  light: {
    background: styles.backgroundColorLight,
  },
  dark: {
    background: styles.backgroundColorDark,
  },
};

но столкнулся со стеной непонимания которая изображена на скриншоте. 
<img width="1280" alt="Screenshot 2022-12-21 at 15 59 24" src="https://user-images.githubusercontent.com/65355827/208892562-945e4df4-92c8-48f1-9e33-bcc4e6c0c509.png">

[В интернете предлагают эту стену дополнительно парсить, мне показалось это некрасивым, поэтому принял непростое решение оставить так](https://github.com/vitejs/vite/discussions/7079)

2022-12-21 11:32 UTC, FedoseevSM commented on packages/client/src/App.tsx
> +import { ThemeContext } from './components/ThemeTogglerButton/ThemeContext';
Отличное решение, но вероятно контекст лучше хранить отдельно от компонента. Компонент, например, можно удалить и заменить на другой, а контекст останется.

Например:
```
import { ThemeContext, themes } from './theme-context';
import ThemeTogglerButton from './theme-toggler-button';

class App extends React.Component {
  constructor(props) {
    super(props);

    this.toggleTheme = () => {
      this.setState((state) => ({
        theme:
          state.theme === themes.dark
            ? themes.light
            : themes.dark,
      }));
    };
```
https://reactdev.ru/handbook/context/#updating-context-from-a-nested-component

2022-12-21 13:39 UTC, helgamir requested changes
Всё отлично, спасибо! есть пара моментов, которые надо поправить.

2022-12-21 13:39 UTC, helgamir commented on packages/client/src/store/theme/ThemeSlice.ts
> +      localStorage.setItem('theme', themeValueFromLocalStorage);
возможно надо везде проверку на доступность localstorage сделать

2022-12-21 13:39 UTC, helgamir commented on packages/client/src/components/Routing/Routing.tsx
> +          <Route index element={<LoginForm login={''} password={''} />} />
Тут такие пустые должны передаваться значения?

2022-12-21 13:39 UTC, helgamir commented on packages/client/src/store/theme/initialSlice.ts
> +const themeValueFromLocalStorage = localStorage.getItem('theme');
тоже бы проверку на доступность localstorage

2022-12-21 13:39 UTC, helgamir commented on packages/client/src/store/theme/initialSlice.ts
> +  theme: theme,
возможно стоит переименовать в activeTheme, чтобы было очевиднее, что это не просто тема, а выбранная сейчас.

2022-12-21 14:05 UTC, user14052020 commented on packages/client/src/components/ThemeTogglerButton/ThemeContext.ts
> +    background: 'rgb(0, 0, 0)',
Любезная Ольга предложила решение, которое решает эту проблему, чуть позже выложу

2022-12-24 09:38 UTC, helgamir approved these changes
Супер! Спасибо!

2022-12-24 09:59 UTC, DianaIvanovna approved these changes

2022-12-24 10:00 UTC, merged