Pra 123 emoji
yandex-team-01/middle.game.praktikum.yandex pull request #57
Opened 2022-12-24 20:58 UTC by DianaIvanovna

[PRA-123 реакции на комментарий](https://linear.app/teamproject/issue/PRA-123/emocii-kommentariev)

Добавила api для работы с реакциями на комментарий.
1. создала модель реакции и 2 запроса 
- **post запрос создание реакции. api/reaction** 
Добавила логику, что если создают второй раз одинаковую реакцию, то api находит по id комментарию, id автору и эмоджи запись и удаляет ее. Нужно чтобы при повторном нажатии на эмоцию происходило удаление 

тело запроса: 
```
{
    "id_comment": "ea8b44d2-2902-4307-aea7-9d1d22fed7f0",
    "id_author": "1",
    "value": "💥",
 }
```
-  **get запрос на все комментарии api/reaction** 
(нужен для удобства разработки)

2. Сделала связь 1:многим для комментария и реакции. При запросе комментариев в поле "Reactions" будет массив всех реакции на данный комментарий

2022-12-24 22:11 UTC, FedoseevSM commented on Dockerfile.server
> +COPY --from=builder /app/packages/server/keys/ /app/keys/
Строчка дублируется 2 раза

2022-12-24 22:11 UTC, FedoseevSM commented on packages/server/index.ts
> +  app.use(router);
Строчка дублируется 2 раза

2022-12-25 06:54 UTC, Victoriya0993 requested changes
Диана, все хорошо! Спасибо за пример связей между таблицами)

Есть предложение придерживаться единого решения по детализации. Давай определимся какой мы выбираем (атомарный или разделенный по общему смыслу)

2022-12-25 06:54 UTC, Victoriya0993 commented on packages/server/db.ts
> +Reaction.belongsTo(Comment, { foreignKey: 'id' });
Классно, что настроила связь между таблицами!

2022-12-25 06:54 UTC, Victoriya0993 commented on packages/server/routing/index.router.ts
> +reactionRouter(apiRouter);
По идее реакция - это часть форума, поэтому ее можно не выносить в отдельный роут, а добавить в forumRouter

2022-12-25 06:54 UTC, Victoriya0993 commented on packages/server/services/reactionServer.ts
> +import { reactionRepos } from '../db';
Если мы принимаем решение хранить все сущности форума (коммент, топик, эмоция и др.) в одном месте, то и сервис у них должен быть общий (все в forumService). В нашем случае мы разделяем более крупные сущности - это Пользователь, Форум, Тема. 
Но можем выбрать бОльшую детализацию, как у тебя. Тогда топик, комментарий также будут иметь свои сервисы и роутеры.

2022-12-27 08:21 UTC, Victoriya0993 approved these changes

2022-12-27 10:07 UTC, FedoseevSM approved these changes
Спасибо, классно получилось! Запросы отрабатывают по хосту localhost:3001/api/forum
Создаётся массив в параметре Reaction у комментария

2022-12-27 10:10 UTC, merged