Pra 112 добавьте возможность переключать темы
yandex-team-01/middle.game.praktikum.yandex pull request #59
Opened 2022-12-27 17:35 UTC by helgamir

Добавлена возможность переключать темы с  сохранением данных пользователя в базе.
Добавлена таблица User в базу. Сохраняется при регистрации пользователя (старых не сохраняет).

## Сценарии
**Если пользователь не залогинен:**
если поменял тему и потом залогинился, то база обновляется.
если меняет тему без логина, то тема сохраняется в куках и подхватывается из них при перезагрузке.

**Если пользователь залогинен:**
Сохраняет нужную тему в базе, берет нужную тему из базы.

## Есть вопросы:
_Есть несколько вопросов по типизации._ В коде они закомменчены ts-ignore. 
Есть вопрос по тому, как синхронизировать initialState в ssr и дефолтную тему на клиенте. Сейчас они совпадают поскольку руками указана одинаковая тема и там и там.

## Как проверить:
`docker-compose up`
Должны собраться контейнеры с базой, pg-admin, клиентом и сервером.
Чтобы проверять в деве, можно запустить только два контейнера - pg-admin и базу.

Сервер запускать `yarn run dev:ssr` Но сначала поменять в файле db.ts на сервере host на localhost. Иначе запросы не будут ходить в базу.

2022-12-27 18:23 UTC, user14052020 approved these changes
За смену title отдельное спасибо)

2023-01-09 06:27 UTC, FedoseevSM commented
`Есть вопрос по тому, как синхронизировать initialState в ssr и дефолтную тему на клиенте. Сейчас они совпадают поскольку руками указана одинаковая тема и там и там.`
Привет! Спасибо за PR. Вероятно, мы сможем устанавливать дефолтную тему через кукисы, если верно понял. К примеру, через запрос, в router: res.cookie('themeCookie', 'dark')
`
import type { Request, Response } from 'express';
import { Router, ErrorRequestHandler, RequestHandler } from 'express';
import { renderHtml } from '../utils/renderHtml';
import { allRoutes } from '../constants/allRoutes';

export const router: Router = Router();

const middlewares: Array<RequestHandler | ErrorRequestHandler> = [];

export function appRoutes(router: Router) {
  router.get(allRoutes, middlewares, function (req: Request, res: Response) {
    res.cookie('themeCookie', 'dark')
    renderHtml(req, res);
  });
}

appRoutes(router);
`

2023-01-09 11:44 UTC, FedoseevSM commented
> `Есть вопрос по тому, как синхронизировать initialState в ssr и дефолтную тему на клиенте. Сейчас они совпадают поскольку руками указана одинаковая тема и там и там.` Привет! Спасибо за PR. Вероятно, мы сможем устанавливать дефолтную тему через кукисы, если верно понял. К примеру, через запрос, в router: res.cookie('themeCookie', 'dark')
> 
> ```
> import { Router, ErrorRequestHandler, RequestHandler } from 'express';
> import { renderHtml } from '../utils/renderHtml';
> import { allRoutes } from '../constants/allRoutes';
> 
> export const router: Router = Router();
> 
> const middlewares: Array<RequestHandler | ErrorRequestHandler> = [];
> 
> export function appRoutes(router: Router) {
>   router.get(allRoutes, middlewares, function (req: Request, res: Response) {
>     res.cookie('themeCookie', 'dark');
>     renderHtml(req, res);
>   });
> }
> 
> appRoutes(router);
> ```

Проще говоря, предложение в SSR делать инициализацию темы через установки кукисов, а на клиенте тема автоматически подхватится от кукисов установленных в SSR. Возможно, роутер не самое удачное место, это пример. Может, быть мидлваря, в которой уже прописана проверка на наличие темы будет лучше

2023-01-09 13:10 UTC, khitrind requested changes
Давай перенесем работу с куками в функции, что в салйсе, что создание инстанса, в остальном все оки вроде

2023-01-09 13:10 UTC, khitrind commented on packages/client/src/constants/themes.ts
> +export const COOKIE_THEME_NAME = 'themeCookie';
```suggestion
export const THEME_LIGTH_NAME = 'light' as const;
export const THEME_DARK_NAME = 'dark' as const;

export const COOKIE_THEME_NAME = 'themeCookie' as const;
```

2023-01-09 13:10 UTC, khitrind commented on packages/client/src/modules/IUser.ts
> +  display_name: string | null;
Думаю лучше сделать их опциональными, а не через null. Меньше проблем будет

2023-01-09 13:10 UTC, khitrind commented on packages/client/src/store/theme/initialSlice.ts
> +}
Давай вот это в функцию оберенм и будем использовать как `activeTheme: getTheme()`, что бы на ssr не словить приколясов

2023-01-09 13:10 UTC, khitrind commented on packages/server/middlewares/auth.ts
> +      res.locals.theme = JSON.parse(user?.theme);
Вроде виктория разбиралась с тем, как res типизировать

2023-01-10 20:52 UTC, merged