Pra 136 bug fixes
yandex-team-01/middle.game.praktikum.yandex pull request #67
Opened 2023-01-23 19:53 UTC by Victoriya0993

### Какую задачу решаем

Небольшие правки:
 - шрифты в инпутах
 - поле пароля скрыто
 - поправлен возврат ошибок в БД

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-01-23 21:48 UTC, khitrind requested changes

2023-01-23 21:48 UTC, khitrind commented on packages/client/src/components/Form/GenericForm.tsx
> +                (!['password', 'repeatPassword'].includes(item)) ?
У инпута просто должно быть поле type, проверка через include тут не нужна. На самом деле тут нарушается принцип открытости закрытости, но если простыми словами, то так при добавлении нового типа придется каждый раз менять GenericForm с полем type мы просто конфижеком это сделаем

2023-01-24 02:48 UTC, user14052020 approved these changes
Спасибо, что взяла это на себя!

2023-01-24 19:36 UTC, Victoriya0993 commented on packages/client/src/components/Form/GenericForm.tsx
> +                (!['password', 'repeatPassword'].includes(item)) ?
Поправила, спасибо)

2023-01-25 09:25 UTC, khitrind approved these changes

2023-01-25 11:06 UTC, merged