Pra 18: Заготовка страницы профиля
yandex-team-01/middle.game.praktikum.yandex pull request #9
Opened 2022-11-04 15:02 UTC by samgxlden

**Заготовка страницы профиля**
https://linear.app/teamproject/issue/PRA-18

**Реализовано:**

- Вёрстка страницы профиля
- Компоненты для страницы профиля
- API для страницы профиля

**Откорректировано:**

- Добавлен label для компонента Input
- Изменены стили в компоненте Form и BlankWindow
- Добавлены переменные в файл env.ts (уже задействовано для fetch в store)

2022-11-04 15:45 UTC, DianaIvanovna commented on packages/client/src/modules/IUsers.ts
> +}
в файле IUser.ts есть очень похожий интерфейс, может он тебе подойдет ?
```
export interface IUser {
  id: number
  first_name: string
  second_name: string
  display_name: string
  login: string
  email: string
  phone: string
  avatar: string
}

```

2022-11-04 16:10 UTC, DianaIvanovna commented on packages/client/src/components/Routing/Routing.tsx
> +import { SettingsChangePassword } from 'src/pages/SettingsPage/components/SettingsChangePassword';
Может объединим их в один файл index.ts внутри SettingsPage?
чтобы сделать 
```
import { SettingsData, SettingsChangeData, SettingsChangePassword }from 'src/pages/SettingsPage/"
```

2022-11-04 16:12 UTC, DianaIvanovna commented on packages/client/src/pages/SettingsPage/SettingsPage.tsx
> +};
почисти код, удали ненужный import Routes, Route, Link и тег <></>
```
import { Outlet } from 'react-router-dom';

import { BlankWindow } from 'src/components/BlankWindow';

export const SettingsPage = () => {
  return (
    <BlankWindow>
      <Outlet />
    </BlankWindow>
  );
};

```

2022-11-04 16:15 UTC, DianaIvanovna commented on packages/client/src/pages/SettingsPage/components/SettingsAvatar/SettingsAvatar.tsx
> +        </div>
у меня аватар не отображается
![image](https://user-images.githubusercontent.com/60156828/200024416-c24513bf-4e32-4bfe-8c2d-b4412b4f3b2e.png)


нужно сделать import картинки 
```
import photo from '../../../../assets/images/no-avatar.png';

export const SettingsAvatar = () => {
  const url = 0;
  return (
    <div className={styles.rounded}>
      {!url && <img src={photo} alt="user_1" />}
    </div>
  );
};

```

2022-11-04 16:18 UTC, DianaIvanovna commented on packages/client/src/pages/SettingsPage/components/SettingsChangeData/SettingsChangeData.tsx
> +  let navigate = useNavigate();
почисти пожалуйста неиспользуемый код, чтобы при  yarn lint --scope=client
не было ошибок 

![image](https://user-images.githubusercontent.com/60156828/200024748-3ed5a72e-4315-4f01-9d50-b717927ea6cb.png)

2022-11-04 16:22 UTC, khitrind requested changes

2022-11-04 16:22 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsAvatar/SettingsAvatar.tsx
> +                <img src="../../../../assets/images/no-avatar.png" alt="user_1" />
Так же стоит исправить alt - alt помогает людям, которые пользуются вебом через скринридеры ориентироваться на странице, user_1 вообще никак им не поможет.
https://htmlacademy.ru/blog/articles/alt-text

2022-11-04 16:22 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsChangeData/SettingsChangeData.tsx
> +  let navigate = useNavigate();
const, переменная не изменяется

2022-11-04 16:22 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsChangeData/SettingsChangeData.tsx
> +          <div key={0}>
Что такое key=0?

2022-11-04 16:22 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsChangeData/SettingsChangeData.tsx
> +              <Button regular onClick={() => navigate(-1)}>
Давай вынесем эту логику в функцию с понятным названием

2022-11-04 16:22 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsChangePassword/SettingsChangePassword.tsx
> +          </div>,
Точно такой же набор вопросов как SettingsChahgeData

2022-11-04 16:22 UTC, khitrind commented on packages/client/src/pages/SettingsPage/components/SettingsData/SettingsData.tsx
> +        </div>
Это стоит вынести в отдельный компонент условный `UserInfo`.

2022-11-04 16:22 UTC, khitrind commented on packages/client/src/store/users/UsersActions.ts
> +    }
Что будет если вылетит огибка, какой алгоритм действий?

2022-11-04 16:27 UTC, DianaIvanovna commented on packages/client/src/store/users/UsersActions.ts
> +);
разве в нашем проекте нужно находить пользователя по логину? ты хочешь в друзья потом добавлять ?

2022-11-04 16:34 UTC, DianaIvanovna reviewed
Нужно поправить сломанную верстку на странице форума и лидерборда и постараться убрать замечания lint

2022-11-06 09:30 UTC, khitrind approved these changes

2022-11-06 10:29 UTC, DianaIvanovna approved these changes

2022-11-06 10:35 UTC, merged